/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: bLa1shfC4noziDsvmxjKJF
// Component: tTCkSMouIA8B

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";
import * as plasmicAuth from "@plasmicapp/react-web/lib/auth";

import { usePlasmicDataSourceContext } from "@plasmicapp/data-sources-context";
import {
  executePlasmicDataOp,
  usePlasmicDataOp,
  usePlasmicInvalidate
} from "@plasmicapp/react-web/lib/data-sources";

import { SmoothScroll } from "../../SmoothScroll"; // plasmic-import: Jfg-9WPWcWFs/codeComponent
import LineBg from "../../LineBg"; // plasmic-import: Gitq1R2yOG92/component
import { ScrollDetector } from "../../ScrollDetector"; // plasmic-import: Q1k6AlFajD5X/codeComponent
import NewMenu from "../../NewMenu"; // plasmic-import: H0Q4YGXvnXjh/component
import TickerHeader from "../../TickerHeader"; // plasmic-import: sVhN06_u5KJ1/component
import Button from "../../Button"; // plasmic-import: VLjK03XBepNB/component
import TemplateCard from "../../TemplateCard"; // plasmic-import: u1Kyfwr4MSZG/component
import { PatternGrid } from "../../PatternGrid"; // plasmic-import: vXuOXgE7vClI/codeComponent
import { RevealOnScroll } from "../../RevealOnScroll"; // plasmic-import: CAuNcrF6_Gj8/codeComponent
import { Video } from "@plasmicpkgs/plasmic-basic-components";
import Section from "../../Section"; // plasmic-import: rBKpW-lDXfWK/component
import FotterMain from "../../FotterMain"; // plasmic-import: pJp_GqmWQ71r/component
import { Fetcher } from "@plasmicapp/react-web/lib/data-sources";
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: bLa1shfC4noziDsvmxjKJF/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: bLa1shfC4noziDsvmxjKJF/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: bLa1shfC4noziDsvmxjKJF/projectcss
import sty from "./PlasmicWorks.module.css"; // plasmic-import: tTCkSMouIA8B/css

import CircleIcon from "./icons/PlasmicIcon__Circle"; // plasmic-import: I6R9tdLXkQer/icon
import ChevronRightIcon from "./icons/PlasmicIcon__ChevronRight"; // plasmic-import: dlvUo4g-Sy-8/icon
import ChevronDownIcon from "./icons/PlasmicIcon__ChevronDown"; // plasmic-import: XVSFhUeRi9UU/icon
import Artboard14SvgIcon from "./icons/PlasmicIcon__Artboard14Svg"; // plasmic-import: RNiMy76HG5_X/icon

const emptyProxy: any = new Proxy(() => "", {
  get(_, prop) {
    return prop === Symbol.toPrimitive ? () => "" : emptyProxy;
  }
});

function wrapQueriesWithLoadingProxy($q: any): any {
  return new Proxy($q, {
    get(target, queryName) {
      const query = target[queryName];
      return !query || query.isLoading || !query.data ? emptyProxy : query;
    }
  });
}

export function generateDynamicMetadata($q: any, $ctx: any) {
  return {
    title: "Home",

    openGraph: {
      title: "Home"
    },
    twitter: {
      card: "summary",
      title: "Home"
    }
  };
}

createPlasmicElementProxy;

export type PlasmicWorks__VariantMembers = {};
export type PlasmicWorks__VariantsArgs = {};
type VariantPropType = keyof PlasmicWorks__VariantsArgs;
export const PlasmicWorks__VariantProps = new Array<VariantPropType>();

export type PlasmicWorks__ArgsType = {};
type ArgPropType = keyof PlasmicWorks__ArgsType;
export const PlasmicWorks__ArgProps = new Array<ArgPropType>();

export type PlasmicWorks__OverridesType = {
  root?: Flex__<"div">;
  smoothScroll?: Flex__<typeof SmoothScroll>;
  scrollDetector?: Flex__<typeof ScrollDetector>;
  newMenu?: Flex__<typeof NewMenu>;
  tickerHeader?: Flex__<typeof TickerHeader>;
  headerHeroSection?: Flex__<"div">;
  loved?: Flex__<"div">;
  variant1?: Flex__<"div">;
  _1?: Flex__<"div">;
  img?: Flex__<"div">;
  e9Q1LJl0QxOyx3A5ZmM8Jeght0YJpg?: Flex__<"div">;
  _2?: Flex__<"div">;
  img2?: Flex__<"div">;
  tq5Y4EoZfzzak1F6Iy2LfoUgyl8Jpg?: Flex__<"div">;
  _3?: Flex__<"div">;
  img3?: Flex__<"div">;
  hYcxfv8XWpTIxIwnhNj33Hl2Lq4Jpg?: Flex__<"div">;
  _4?: Flex__<"div">;
  img4?: Flex__<"div">;
  _069SD4E4Rbd50L3X97XsgTvpcJpg?: Flex__<"div">;
  _5?: Flex__<"div">;
  img5?: Flex__<"div">;
  vk7E0Slt7OvlQa7QVqyREh2TxqcJpg?: Flex__<"div">;
  ratingDetails?: Flex__<"div">;
  ratingInfo?: Flex__<"div">;
  ratingScore?: Flex__<"div">;
  container?: Flex__<"div">;
  starsContainer?: Flex__<"div">;
  svg?: Flex__<"div">;
  ratingText?: Flex__<"div">;
  container2?: Flex__<"div">;
  headerHeroSection4?: Flex__<"div">;
  headerHeroSection3?: Flex__<"div">;
  sectionCards3?: Flex__<"div">;
  container49?: Flex__<"div">;
  patternGrid?: Flex__<typeof PatternGrid>;
  htmlVideo4?: Flex__<typeof Video>;
  service05?: Flex__<"div">;
  service15?: Flex__<"div">;
  service25?: Flex__<"div">;
  service35?: Flex__<"div">;
  service45?: Flex__<"div">;
  service55?: Flex__<"div">;
  section?: Flex__<typeof Section>;
};

export interface DefaultWorksProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicWorks__RenderFunc(props: {
  variants: PlasmicWorks__VariantsArgs;
  args: PlasmicWorks__ArgsType;
  overrides: PlasmicWorks__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const globalVariants = _useGlobalVariants();

  const currentUser = useCurrentUser?.() || {};

  let [$queries, setDollarQueries] = React.useState<
    Record<string, ReturnType<typeof usePlasmicDataOp>>
  >({});

  const new$Queries: Record<string, ReturnType<typeof usePlasmicDataOp>> = {
    works: usePlasmicDataOp(() => {
      return {
        sourceId: "n45tEsvLE6YKJCZTUdqEgQ",
        opId: "906a42fb-444b-46bb-a4ff-edd2e0f16ab1",
        userArgs: {},
        cacheKey: `plasmic.$.906a42fb-444b-46bb-a4ff-edd2e0f16ab1.$.`,
        invalidatedKeys: null,
        roleId: null
      };
    })
  };
  if (Object.keys(new$Queries).some(k => new$Queries[k] !== $queries[k])) {
    setDollarQueries(new$Queries);

    $queries = new$Queries;
  }

  const pageMetadata = generateDynamicMetadata(
    wrapQueriesWithLoadingProxy({}),
    $ctx
  );

  const styleTokensClassNames = _useStyleTokens();

  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary" />
        <title key="title">{pageMetadata.title}</title>
        <meta key="og:title" property="og:title" content={pageMetadata.title} />
        <meta
          key="twitter:title"
          property="twitter:title"
          content={pageMetadata.title}
        />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            styleTokensClassNames,
            sty.root
          )}
        >
          <SmoothScroll
            data-plasmic-name={"smoothScroll"}
            data-plasmic-override={overrides.smoothScroll}
            className={classNames("__wab_instance", sty.smoothScroll)}
            duration={1.2}
            wheelMultiplier={1}
          >
            <div className={classNames(projectcss.all, sty.freeBox__jmxHv)}>
              <div className={classNames(projectcss.all, sty.freeBox__lEpwG)}>
                <LineBg
                  className={classNames("__wab_instance", sty.lineBg__wJgIr)}
                />
              </div>
              <ScrollDetector
                data-plasmic-name={"scrollDetector"}
                data-plasmic-override={overrides.scrollDetector}
                className={classNames("__wab_instance", sty.scrollDetector)}
                threshold={50}
              >
                <DataCtxReader__>
                  {$ctx => (
                    <NewMenu
                      data-plasmic-name={"newMenu"}
                      data-plasmic-override={overrides.newMenu}
                      activePage={"works"}
                      className={classNames("__wab_instance", sty.newMenu)}
                      headerTitle={"[ 2026 ]"}
                      scrolledState={(() => {
                        try {
                          return $ctx.scrollData.isScrolled;
                        } catch (e) {
                          if (
                            e instanceof TypeError ||
                            e?.plasmicType === "PlasmicUndefinedDataError"
                          ) {
                            return [];
                          }
                          throw e;
                        }
                      })()}
                    />
                  )}
                </DataCtxReader__>
              </ScrollDetector>
              <TickerHeader
                data-plasmic-name={"tickerHeader"}
                data-plasmic-override={overrides.tickerHeader}
                className={classNames("__wab_instance", sty.tickerHeader)}
              />

              <div
                data-plasmic-name={"headerHeroSection"}
                data-plasmic-override={overrides.headerHeroSection}
                className={classNames(projectcss.all, sty.headerHeroSection)}
              >
                <div className={classNames(projectcss.all, sty.freeBox__wo9Dy)}>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__fUTzO)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        sty.freeBox___7DKz0
                      )}
                    >
                      <h1
                        className={classNames(
                          projectcss.all,
                          projectcss.h1,
                          projectcss.__wab_text,
                          sty.h1__czfVh
                        )}
                      >
                        {"You don't need\r"}
                      </h1>
                    </div>
                    <h1
                      className={classNames(
                        projectcss.all,
                        projectcss.h1,
                        projectcss.__wab_text,
                        sty.h1__tuaGm
                      )}
                    >
                      {"You need a powerful\r"}
                    </h1>
                    <h1
                      className={classNames(
                        projectcss.all,
                        projectcss.h1,
                        projectcss.__wab_text,
                        sty.h1__bjaYl
                      )}
                    >
                      {"\rwebsite template."}
                    </h1>
                    <div
                      className={classNames(projectcss.all, sty.freeBox__xTnIx)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__gcHxx
                        )}
                      >
                        {
                          "Launch a stunning website that looks like you hired a top design agency. In days.\r"
                        }
                      </div>
                      <div
                        data-plasmic-name={"loved"}
                        data-plasmic-override={overrides.loved}
                        className={classNames(projectcss.all, sty.loved)}
                      >
                        <div
                          data-plasmic-name={"variant1"}
                          data-plasmic-override={overrides.variant1}
                          className={classNames(projectcss.all, sty.variant1)}
                        >
                          <div
                            data-plasmic-name={"_1"}
                            data-plasmic-override={overrides._1}
                            className={classNames(projectcss.all, sty._1)}
                          >
                            <div
                              data-plasmic-name={"img"}
                              data-plasmic-override={overrides.img}
                              className={classNames(projectcss.all, sty.img)}
                            >
                              <div
                                data-plasmic-name={
                                  "e9Q1LJl0QxOyx3A5ZmM8Jeght0YJpg"
                                }
                                data-plasmic-override={
                                  overrides.e9Q1LJl0QxOyx3A5ZmM8Jeght0YJpg
                                }
                                className={classNames(
                                  projectcss.all,
                                  sty.e9Q1LJl0QxOyx3A5ZmM8Jeght0YJpg
                                )}
                              />
                            </div>
                          </div>
                          <div
                            data-plasmic-name={"_2"}
                            data-plasmic-override={overrides._2}
                            className={classNames(projectcss.all, sty._2)}
                          >
                            <div
                              data-plasmic-name={"img2"}
                              data-plasmic-override={overrides.img2}
                              className={classNames(projectcss.all, sty.img2)}
                            >
                              <div
                                data-plasmic-name={
                                  "tq5Y4EoZfzzak1F6Iy2LfoUgyl8Jpg"
                                }
                                data-plasmic-override={
                                  overrides.tq5Y4EoZfzzak1F6Iy2LfoUgyl8Jpg
                                }
                                className={classNames(
                                  projectcss.all,
                                  sty.tq5Y4EoZfzzak1F6Iy2LfoUgyl8Jpg
                                )}
                              />
                            </div>
                          </div>
                          <div
                            data-plasmic-name={"_3"}
                            data-plasmic-override={overrides._3}
                            className={classNames(projectcss.all, sty._3)}
                          >
                            <div
                              data-plasmic-name={"img3"}
                              data-plasmic-override={overrides.img3}
                              className={classNames(projectcss.all, sty.img3)}
                            >
                              <div
                                data-plasmic-name={
                                  "hYcxfv8XWpTIxIwnhNj33Hl2Lq4Jpg"
                                }
                                data-plasmic-override={
                                  overrides.hYcxfv8XWpTIxIwnhNj33Hl2Lq4Jpg
                                }
                                className={classNames(
                                  projectcss.all,
                                  sty.hYcxfv8XWpTIxIwnhNj33Hl2Lq4Jpg
                                )}
                              />
                            </div>
                          </div>
                          <div
                            data-plasmic-name={"_4"}
                            data-plasmic-override={overrides._4}
                            className={classNames(projectcss.all, sty._4)}
                          >
                            <div
                              data-plasmic-name={"img4"}
                              data-plasmic-override={overrides.img4}
                              className={classNames(projectcss.all, sty.img4)}
                            >
                              <div
                                data-plasmic-name={
                                  "_069SD4E4Rbd50L3X97XsgTvpcJpg"
                                }
                                data-plasmic-override={
                                  overrides._069SD4E4Rbd50L3X97XsgTvpcJpg
                                }
                                className={classNames(
                                  projectcss.all,
                                  sty._069Sd4E4Rbd50L3X97XsgTvpcJpg
                                )}
                              />
                            </div>
                          </div>
                          <div
                            data-plasmic-name={"_5"}
                            data-plasmic-override={overrides._5}
                            className={classNames(projectcss.all, sty._5)}
                          >
                            <div
                              data-plasmic-name={"img5"}
                              data-plasmic-override={overrides.img5}
                              className={classNames(projectcss.all, sty.img5)}
                            >
                              <div
                                data-plasmic-name={
                                  "vk7E0Slt7OvlQa7QVqyREh2TxqcJpg"
                                }
                                data-plasmic-override={
                                  overrides.vk7E0Slt7OvlQa7QVqyREh2TxqcJpg
                                }
                                className={classNames(
                                  projectcss.all,
                                  sty.vk7E0Slt7OvlQa7QVqyREh2TxqcJpg
                                )}
                              />
                            </div>
                          </div>
                          <div
                            data-plasmic-name={"ratingDetails"}
                            data-plasmic-override={overrides.ratingDetails}
                            className={classNames(
                              projectcss.all,
                              sty.ratingDetails
                            )}
                          >
                            <div
                              data-plasmic-name={"ratingInfo"}
                              data-plasmic-override={overrides.ratingInfo}
                              className={classNames(
                                projectcss.all,
                                sty.ratingInfo
                              )}
                            >
                              <div
                                data-plasmic-name={"ratingScore"}
                                data-plasmic-override={overrides.ratingScore}
                                className={classNames(
                                  projectcss.all,
                                  sty.ratingScore
                                )}
                              >
                                <div
                                  data-plasmic-name={"container"}
                                  data-plasmic-override={overrides.container}
                                  className={classNames(
                                    projectcss.all,
                                    sty.container
                                  )}
                                >
                                  <div
                                    className={classNames(
                                      projectcss.all,
                                      projectcss.__wab_text,
                                      sty.text__hgk2Q
                                    )}
                                  >
                                    {"4.9 / 5"}
                                  </div>
                                </div>
                              </div>
                              <div
                                data-plasmic-name={"starsContainer"}
                                data-plasmic-override={overrides.starsContainer}
                                className={classNames(
                                  projectcss.all,
                                  sty.starsContainer
                                )}
                              >
                                <div
                                  data-plasmic-name={"svg"}
                                  data-plasmic-override={overrides.svg}
                                  className={classNames(
                                    projectcss.all,
                                    sty.svg
                                  )}
                                >
                                  <PlasmicImg__
                                    alt={""}
                                    className={classNames(sty.img__x3PM)}
                                    displayHeight={"10px"}
                                    displayMaxHeight={"none"}
                                    displayMaxWidth={"100%"}
                                    displayMinHeight={"0"}
                                    displayMinWidth={"0"}
                                    displayWidth={"53px"}
                                    loading={"lazy"}
                                    src={{
                                      src: "/plasmic/son_vo/images/svg20128190053524.svg",
                                      fullWidth: 53,
                                      fullHeight: 10,
                                      aspectRatio: undefined
                                    }}
                                  />
                                </div>
                              </div>
                            </div>
                            <div
                              data-plasmic-name={"ratingText"}
                              data-plasmic-override={overrides.ratingText}
                              className={classNames(
                                projectcss.all,
                                sty.ratingText
                              )}
                            >
                              <div
                                data-plasmic-name={"container2"}
                                data-plasmic-override={overrides.container2}
                                className={classNames(
                                  projectcss.all,
                                  sty.container2
                                )}
                              >
                                <div
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.__wab_text,
                                    sty.text__ek6Jt
                                  )}
                                >
                                  {"Loved by 5 833+ creators"}
                                </div>
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.freeBox___22SM)}
                    >
                      <Button
                        className={classNames(
                          "__wab_instance",
                          sty.button___6736P
                        )}
                        end={
                          <ChevronRightIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__n8W6B
                            )}
                            role={"img"}
                          />
                        }
                        iconEnd={true}
                        label={
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__e2Nva
                            )}
                          >
                            {"Check Our Templates"}
                          </div>
                        }
                        linkTo={"#"}
                        size={"extraLarge"}
                      />

                      <Button
                        className={classNames(
                          "__wab_instance",
                          sty.button__aEiCx
                        )}
                        label={
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__suOup
                            )}
                          >
                            {"Check Our Case Study"}
                          </div>
                        }
                        linkTo={"#"}
                        size={"extraLarge"}
                        type={"bordered"}
                      />
                    </div>
                  </div>
                </div>
              </div>
              <div
                data-plasmic-name={"headerHeroSection4"}
                data-plasmic-override={overrides.headerHeroSection4}
                className={classNames(projectcss.all, sty.headerHeroSection4)}
              >
                <div className={classNames(projectcss.all, sty.freeBox__exuy7)}>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__bhbVe)}
                  >
                    <h1
                      className={classNames(
                        projectcss.all,
                        projectcss.h1,
                        projectcss.__wab_text,
                        sty.h1__asJid
                      )}
                    >
                      {"WO"}
                    </h1>
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__y7Ofn)}
                  >
                    <h1
                      className={classNames(
                        projectcss.all,
                        projectcss.h1,
                        projectcss.__wab_text,
                        sty.h1__kAy9W
                      )}
                    >
                      {"H"}
                    </h1>
                    <h1
                      className={classNames(
                        projectcss.all,
                        projectcss.h1,
                        projectcss.__wab_text,
                        sty.h1__nIj0
                      )}
                    >
                      {"S"}
                    </h1>
                    <h1
                      className={classNames(
                        projectcss.all,
                        projectcss.h1,
                        projectcss.__wab_text,
                        sty.h1__q8W0U
                      )}
                    >
                      {"V"}
                    </h1>
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__bxJq4)}
                  >
                    <h1
                      className={classNames(
                        projectcss.all,
                        projectcss.h1,
                        projectcss.__wab_text,
                        sty.h1__maMnc
                      )}
                    >
                      {"RK"}
                    </h1>
                  </div>
                </div>
              </div>
              <div
                data-plasmic-name={"headerHeroSection3"}
                data-plasmic-override={overrides.headerHeroSection3}
                className={classNames(projectcss.all, sty.headerHeroSection3)}
              >
                <h1
                  className={classNames(
                    projectcss.all,
                    projectcss.h1,
                    projectcss.__wab_text,
                    sty.h1__xfsmG
                  )}
                >
                  {"[ "}
                </h1>
                <h1
                  className={classNames(
                    projectcss.all,
                    projectcss.h1,
                    projectcss.__wab_text,
                    sty.h1___4905H
                  )}
                >
                  <React.Fragment>
                    {(() => {
                      try {
                        return $queries.works.data.length;
                      } catch (e) {
                        if (
                          e instanceof TypeError ||
                          e?.plasmicType === "PlasmicUndefinedDataError"
                        ) {
                          return "10 ";
                        }
                        throw e;
                      }
                    })()}
                  </React.Fragment>
                </h1>
                <h1
                  className={classNames(
                    projectcss.all,
                    projectcss.h1,
                    projectcss.__wab_text,
                    sty.h1__mNq9S
                  )}
                >
                  {" "}
                </h1>
                <h1
                  className={classNames(
                    projectcss.all,
                    projectcss.h1,
                    projectcss.__wab_text,
                    sty.h1__gfPmt
                  )}
                >
                  {"FEATURED PROJECTS ]\r\n\r"}
                </h1>
              </div>
              <div
                data-plasmic-name={"sectionCards3"}
                data-plasmic-override={overrides.sectionCards3}
                className={classNames(projectcss.all, sty.sectionCards3)}
              >
                <div
                  data-plasmic-name={"container49"}
                  data-plasmic-override={overrides.container49}
                  className={classNames(projectcss.all, sty.container49)}
                >
                  <div
                    className={classNames(projectcss.all, sty.freeBox__gvyPv)}
                  >
                    <TemplateCard
                      className={classNames(
                        "__wab_instance",
                        sty.templateCard__lgUiq
                      )}
                      img2={
                        <PlasmicImg__
                          alt={""}
                          className={classNames(sty.img__qO0X)}
                          displayHeight={"334px"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"100%"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"100%"}
                          loading={"lazy"}
                          src={{
                            src: "/plasmic/son_vo/images/frame20Jpg.jpg",
                            fullWidth: 511,
                            fullHeight: 596,
                            aspectRatio: undefined
                          }}
                        />
                      }
                      softwareContainerSoftware2={
                        <React.Fragment>
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__hg97L
                            )}
                          >
                            <Artboard14SvgIcon
                              className={classNames(
                                projectcss.all,
                                sty.svg__y42DP
                              )}
                              role={"img"}
                            />
                          </div>
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__f6Fj
                            )}
                          >
                            {"Framer"}
                          </div>
                        </React.Fragment>
                      }
                    />

                    <TemplateCard
                      className={classNames(
                        "__wab_instance",
                        sty.templateCard__sOrUu
                      )}
                      img2={
                        <PlasmicImg__
                          alt={""}
                          className={classNames(sty.img__diZn9)}
                          displayHeight={"334px"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"100%"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"100%"}
                          loading={"lazy"}
                          src={{
                            src: "/plasmic/son_vo/images/frame20Jpg.jpg",
                            fullWidth: 511,
                            fullHeight: 596,
                            aspectRatio: undefined
                          }}
                        />
                      }
                      softwareContainerSoftware2={
                        <React.Fragment>
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__vUsJh
                            )}
                          >
                            <Artboard14SvgIcon
                              className={classNames(
                                projectcss.all,
                                sty.svg__z2VrK
                              )}
                              role={"img"}
                            />
                          </div>
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__edS1L
                            )}
                          >
                            {"Framer"}
                          </div>
                        </React.Fragment>
                      }
                    />

                    <TemplateCard
                      className={classNames(
                        "__wab_instance",
                        sty.templateCard___98G8R
                      )}
                      img2={
                        <PlasmicImg__
                          alt={""}
                          className={classNames(sty.img__sfjE)}
                          displayHeight={"334px"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"100%"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"100%"}
                          loading={"lazy"}
                          src={{
                            src: "/plasmic/son_vo/images/frame20Jpg.jpg",
                            fullWidth: 511,
                            fullHeight: 596,
                            aspectRatio: undefined
                          }}
                        />
                      }
                    />

                    <TemplateCard
                      className={classNames(
                        "__wab_instance",
                        sty.templateCard__b7MMh
                      )}
                      img2={
                        <PlasmicImg__
                          alt={""}
                          className={classNames(sty.img___2C6MI)}
                          displayHeight={"334px"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"100%"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"100%"}
                          loading={"lazy"}
                          src={{
                            src: "/plasmic/son_vo/images/frame20Jpg.jpg",
                            fullWidth: 511,
                            fullHeight: 596,
                            aspectRatio: undefined
                          }}
                        />
                      }
                    />

                    <TemplateCard
                      className={classNames(
                        "__wab_instance",
                        sty.templateCard__ifhTa
                      )}
                      img2={
                        <PlasmicImg__
                          alt={""}
                          className={classNames(sty.img__nGdnb)}
                          displayHeight={"334px"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"100%"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"100%"}
                          loading={"lazy"}
                          src={{
                            src: "/plasmic/son_vo/images/frame20Jpg.jpg",
                            fullWidth: 511,
                            fullHeight: 596,
                            aspectRatio: undefined
                          }}
                        />
                      }
                    />

                    <TemplateCard
                      className={classNames(
                        "__wab_instance",
                        sty.templateCard__yrhBw
                      )}
                      img2={
                        <PlasmicImg__
                          alt={""}
                          className={classNames(sty.img__xmq1G)}
                          displayHeight={"334px"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"100%"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"100%"}
                          loading={"lazy"}
                          src={{
                            src: "/plasmic/son_vo/images/frame20Jpg.jpg",
                            fullWidth: 511,
                            fullHeight: 596,
                            aspectRatio: undefined
                          }}
                        />
                      }
                      softwareContainerSoftware2={
                        <React.Fragment>
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__scqcp
                            )}
                          >
                            <Artboard14SvgIcon
                              className={classNames(
                                projectcss.all,
                                sty.svg__j3Ilj
                              )}
                              role={"img"}
                            />
                          </div>
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__tQpPj
                            )}
                          >
                            {"Framer"}
                          </div>
                        </React.Fragment>
                      }
                    />

                    <TemplateCard
                      className={classNames(
                        "__wab_instance",
                        sty.templateCard__bNnCu
                      )}
                      img2={
                        <PlasmicImg__
                          alt={""}
                          className={classNames(sty.img__rA6I)}
                          displayHeight={"334px"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"100%"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"100%"}
                          loading={"lazy"}
                          src={{
                            src: "/plasmic/son_vo/images/frame20Jpg.jpg",
                            fullWidth: 511,
                            fullHeight: 596,
                            aspectRatio: undefined
                          }}
                        />
                      }
                      softwareContainerSoftware2={
                        <React.Fragment>
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__lzaEa
                            )}
                          >
                            <Artboard14SvgIcon
                              className={classNames(
                                projectcss.all,
                                sty.svg__rjEym
                              )}
                              role={"img"}
                            />
                          </div>
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__wwLCu
                            )}
                          >
                            {"Framer"}
                          </div>
                        </React.Fragment>
                      }
                    />

                    <TemplateCard
                      className={classNames(
                        "__wab_instance",
                        sty.templateCard___7M4Ry
                      )}
                      img2={
                        <PlasmicImg__
                          alt={""}
                          className={classNames(sty.img__fcnpR)}
                          displayHeight={"334px"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"100%"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"100%"}
                          loading={"lazy"}
                          src={{
                            src: "/plasmic/son_vo/images/frame20Jpg.jpg",
                            fullWidth: 511,
                            fullHeight: 596,
                            aspectRatio: undefined
                          }}
                        />
                      }
                      softwareContainerSoftware2={
                        <React.Fragment>
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__jnEii
                            )}
                          >
                            <Artboard14SvgIcon
                              className={classNames(
                                projectcss.all,
                                sty.svg___6Vy3U
                              )}
                              role={"img"}
                            />
                          </div>
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__dn7KD
                            )}
                          >
                            {"Framer"}
                          </div>
                        </React.Fragment>
                      }
                    />
                  </div>
                  <PatternGrid
                    data-plasmic-name={"patternGrid"}
                    data-plasmic-override={overrides.patternGrid}
                    className={classNames("__wab_instance", sty.patternGrid)}
                    gap={24}
                  >
                    {(_par =>
                      !_par ? [] : Array.isArray(_par) ? _par : [_par])(
                      (() => {
                        try {
                          return $queries.works.data;
                        } catch (e) {
                          if (
                            e instanceof TypeError ||
                            e?.plasmicType === "PlasmicUndefinedDataError"
                          ) {
                            return [];
                          }
                          throw e;
                        }
                      })()
                    ).map((__plasmic_item_0, __plasmic_idx_0) => {
                      const currentItem = __plasmic_item_0;
                      const currentIndex = __plasmic_idx_0;
                      return (
                        <RevealOnScroll
                          className={classNames(
                            "__wab_instance",
                            sty.revealOnScroll___07YrR
                          )}
                          delay={(() => {
                            try {
                              return 0.5 * $ctx.plasmicIndex;
                            } catch (e) {
                              if (
                                e instanceof TypeError ||
                                e?.plasmicType === "PlasmicUndefinedDataError"
                              ) {
                                return 0;
                              }
                              throw e;
                            }
                          })()}
                          duration={0.8}
                          key={currentIndex}
                          yOffset={50}
                        >
                          <TemplateCard
                            className={classNames(
                              "__wab_instance",
                              sty.templateCard__f1Lha
                            )}
                            container9={
                              <PlasmicLink__
                                className={classNames(
                                  projectcss.all,
                                  projectcss.a,
                                  projectcss.__wab_text,
                                  sty.link__rm3FP
                                )}
                                component={Link}
                                href={`/works/${currentItem.Slug}`}
                                legacyBehavior={false}
                                platform={"nextjs"}
                              >
                                <React.Fragment>
                                  {(() => {
                                    try {
                                      return currentItem.Title;
                                    } catch (e) {
                                      if (
                                        e instanceof TypeError ||
                                        e?.plasmicType ===
                                          "PlasmicUndefinedDataError"
                                      ) {
                                        return "Vectura";
                                      }
                                      throw e;
                                    }
                                  })()}
                                </React.Fragment>
                              </PlasmicLink__>
                            }
                            img2={
                              <PlasmicLink__
                                className={classNames(
                                  projectcss.all,
                                  projectcss.a,
                                  sty.link__izGY
                                )}
                                component={Link}
                                href={`/works/${currentItem.Slug}`}
                                legacyBehavior={false}
                                platform={"nextjs"}
                              >
                                {(() => {
                                  try {
                                    return currentItem["Video"];
                                  } catch (e) {
                                    if (
                                      e instanceof TypeError ||
                                      e?.plasmicType ===
                                        "PlasmicUndefinedDataError"
                                    ) {
                                      return true;
                                    }
                                    throw e;
                                  }
                                })() ? (
                                  <Video
                                    data-plasmic-name={"htmlVideo4"}
                                    data-plasmic-override={overrides.htmlVideo4}
                                    autoPlay={true}
                                    className={classNames(
                                      "__wab_instance",
                                      sty.htmlVideo4
                                    )}
                                    controls={false}
                                    loop={true}
                                    muted={true}
                                    ref={ref => {
                                      $refs["htmlVideo4"] = ref;
                                    }}
                                    src={currentItem.Video}
                                  />
                                ) : null}
                                {(() => {
                                  try {
                                    return !currentItem["Video"];
                                  } catch (e) {
                                    if (
                                      e instanceof TypeError ||
                                      e?.plasmicType ===
                                        "PlasmicUndefinedDataError"
                                    ) {
                                      return true;
                                    }
                                    throw e;
                                  }
                                })() ? (
                                  <PlasmicImg__
                                    alt={""}
                                    className={classNames(sty.img__x8Wf7)}
                                    displayHeight={"auto"}
                                    displayMaxHeight={"none"}
                                    displayMaxWidth={"100%"}
                                    displayMinHeight={"0"}
                                    displayMinWidth={"0"}
                                    displayWidth={"100%"}
                                    loading={"lazy"}
                                    src={(() => {
                                      try {
                                        return currentItem["Main Image"];
                                      } catch (e) {
                                        if (
                                          e instanceof TypeError ||
                                          e?.plasmicType ===
                                            "PlasmicUndefinedDataError"
                                        ) {
                                          return {
                                            src: "/plasmic/son_vo/images/frame20Jpg.jpg",
                                            fullWidth: 511,
                                            fullHeight: 596,
                                            aspectRatio: undefined
                                          };
                                        }
                                        throw e;
                                      }
                                    })()}
                                  />
                                ) : null}
                              </PlasmicLink__>
                            }
                            softwareContainerSoftware2={
                              <div
                                className={classNames(
                                  projectcss.all,
                                  sty.freeBox___304
                                )}
                              >
                                {(() => {
                                  try {
                                    return (
                                      currentItem.Services &&
                                      currentItem.Services.includes(
                                        "UI/UX Design"
                                      )
                                    );
                                  } catch (e) {
                                    if (
                                      e instanceof TypeError ||
                                      e?.plasmicType ===
                                        "PlasmicUndefinedDataError"
                                    ) {
                                      return true;
                                    }
                                    throw e;
                                  }
                                })() ? (
                                  <div
                                    data-plasmic-name={"service05"}
                                    data-plasmic-override={overrides.service05}
                                    className={classNames(
                                      projectcss.all,
                                      sty.service05
                                    )}
                                  >
                                    <div
                                      className={classNames(
                                        projectcss.all,
                                        projectcss.__wab_text,
                                        sty.text__f7Hw2
                                      )}
                                    >
                                      {"UI/UX Design"}
                                    </div>
                                  </div>
                                ) : null}
                                {(() => {
                                  try {
                                    return (
                                      currentItem.Services &&
                                      currentItem.Services.includes(
                                        "E-commerce"
                                      )
                                    );
                                  } catch (e) {
                                    if (
                                      e instanceof TypeError ||
                                      e?.plasmicType ===
                                        "PlasmicUndefinedDataError"
                                    ) {
                                      return true;
                                    }
                                    throw e;
                                  }
                                })() ? (
                                  <div
                                    data-plasmic-name={"service15"}
                                    data-plasmic-override={overrides.service15}
                                    className={classNames(
                                      projectcss.all,
                                      sty.service15
                                    )}
                                  >
                                    <div
                                      className={classNames(
                                        projectcss.all,
                                        projectcss.__wab_text,
                                        sty.text__b9H2Y
                                      )}
                                    >
                                      {"E-commerce"}
                                    </div>
                                  </div>
                                ) : null}
                                {(() => {
                                  try {
                                    return (
                                      currentItem.Services &&
                                      currentItem.Services.includes("SEO")
                                    );
                                  } catch (e) {
                                    if (
                                      e instanceof TypeError ||
                                      e?.plasmicType ===
                                        "PlasmicUndefinedDataError"
                                    ) {
                                      return true;
                                    }
                                    throw e;
                                  }
                                })() ? (
                                  <div
                                    data-plasmic-name={"service25"}
                                    data-plasmic-override={overrides.service25}
                                    className={classNames(
                                      projectcss.all,
                                      sty.service25
                                    )}
                                  >
                                    <div
                                      className={classNames(
                                        projectcss.all,
                                        projectcss.__wab_text,
                                        sty.text__mXaRk
                                      )}
                                    >
                                      {"SEO"}
                                    </div>
                                  </div>
                                ) : null}
                                {(() => {
                                  try {
                                    return (
                                      currentItem.Services &&
                                      currentItem.Services.includes("Content")
                                    );
                                  } catch (e) {
                                    if (
                                      e instanceof TypeError ||
                                      e?.plasmicType ===
                                        "PlasmicUndefinedDataError"
                                    ) {
                                      return true;
                                    }
                                    throw e;
                                  }
                                })() ? (
                                  <div
                                    data-plasmic-name={"service35"}
                                    data-plasmic-override={overrides.service35}
                                    className={classNames(
                                      projectcss.all,
                                      sty.service35
                                    )}
                                  >
                                    <div
                                      className={classNames(
                                        projectcss.all,
                                        projectcss.__wab_text,
                                        sty.text___6Mveo
                                      )}
                                    >
                                      {"Content"}
                                    </div>
                                  </div>
                                ) : null}
                                {(() => {
                                  try {
                                    return (
                                      currentItem.Services &&
                                      currentItem.Services.includes(
                                        "Brand Idenity"
                                      )
                                    );
                                  } catch (e) {
                                    if (
                                      e instanceof TypeError ||
                                      e?.plasmicType ===
                                        "PlasmicUndefinedDataError"
                                    ) {
                                      return true;
                                    }
                                    throw e;
                                  }
                                })() ? (
                                  <div
                                    data-plasmic-name={"service45"}
                                    data-plasmic-override={overrides.service45}
                                    className={classNames(
                                      projectcss.all,
                                      sty.service45
                                    )}
                                  >
                                    <div
                                      className={classNames(
                                        projectcss.all,
                                        projectcss.__wab_text,
                                        sty.text__p5Jz
                                      )}
                                    >
                                      {"Brand Idenity"}
                                    </div>
                                  </div>
                                ) : null}
                                {(() => {
                                  try {
                                    return (
                                      currentItem.Services &&
                                      currentItem.Services.includes(
                                        "Web Development"
                                      )
                                    );
                                  } catch (e) {
                                    if (
                                      e instanceof TypeError ||
                                      e?.plasmicType ===
                                        "PlasmicUndefinedDataError"
                                    ) {
                                      return true;
                                    }
                                    throw e;
                                  }
                                })() ? (
                                  <div
                                    data-plasmic-name={"service55"}
                                    data-plasmic-override={overrides.service55}
                                    className={classNames(
                                      projectcss.all,
                                      sty.service55
                                    )}
                                  >
                                    <div
                                      className={classNames(
                                        projectcss.all,
                                        projectcss.__wab_text,
                                        sty.text___6KvRw
                                      )}
                                    >
                                      {"Web Development"}
                                    </div>
                                  </div>
                                ) : null}
                              </div>
                            }
                          />
                        </RevealOnScroll>
                      );
                    })}
                  </PatternGrid>
                </div>
              </div>
              <RevealOnScroll
                className={classNames(
                  "__wab_instance",
                  sty.revealOnScroll__mArFx
                )}
                delay={0}
                duration={1.6}
                yOffset={100}
              >
                <Section
                  data-plasmic-name={"section"}
                  data-plasmic-override={overrides.section}
                  className={classNames("__wab_instance", sty.section)}
                  size={
                    hasVariant(globalVariants, "screen", "mobile")
                      ? "fullContentWidth"
                      : "fullContentWidth"
                  }
                >
                  <div
                    className={classNames(projectcss.all, sty.freeBox__kg8V9)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__jqhOk)}
                    >
                      <h1
                        className={classNames(
                          projectcss.all,
                          projectcss.h1,
                          projectcss.__wab_text,
                          sty.h1___4LdUv
                        )}
                      >
                        {"WITH ME\n\r"}
                      </h1>
                      <h1
                        className={classNames(
                          projectcss.all,
                          projectcss.h1,
                          projectcss.__wab_text,
                          sty.h1__xs414
                        )}
                      >
                        {"Write the next story\r\n\r"}
                      </h1>
                    </div>
                  </div>
                </Section>
              </RevealOnScroll>
            </div>
            <FotterMain
              className={classNames("__wab_instance", sty.fotterMain___0Yg5A)}
            />

            <FotterMain
              className={classNames("__wab_instance", sty.fotterMain__bRaMl)}
            />

            <div className={classNames(projectcss.all, sty.freeBox__jpMh8)}>
              <LineBg
                className={classNames("__wab_instance", sty.lineBg__dnZqG)}
              />
            </div>
          </SmoothScroll>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "smoothScroll",
    "scrollDetector",
    "newMenu",
    "tickerHeader",
    "headerHeroSection",
    "loved",
    "variant1",
    "_1",
    "img",
    "e9Q1LJl0QxOyx3A5ZmM8Jeght0YJpg",
    "_2",
    "img2",
    "tq5Y4EoZfzzak1F6Iy2LfoUgyl8Jpg",
    "_3",
    "img3",
    "hYcxfv8XWpTIxIwnhNj33Hl2Lq4Jpg",
    "_4",
    "img4",
    "_069SD4E4Rbd50L3X97XsgTvpcJpg",
    "_5",
    "img5",
    "vk7E0Slt7OvlQa7QVqyREh2TxqcJpg",
    "ratingDetails",
    "ratingInfo",
    "ratingScore",
    "container",
    "starsContainer",
    "svg",
    "ratingText",
    "container2",
    "headerHeroSection4",
    "headerHeroSection3",
    "sectionCards3",
    "container49",
    "patternGrid",
    "htmlVideo4",
    "service05",
    "service15",
    "service25",
    "service35",
    "service45",
    "service55",
    "section"
  ],
  smoothScroll: [
    "smoothScroll",
    "scrollDetector",
    "newMenu",
    "tickerHeader",
    "headerHeroSection",
    "loved",
    "variant1",
    "_1",
    "img",
    "e9Q1LJl0QxOyx3A5ZmM8Jeght0YJpg",
    "_2",
    "img2",
    "tq5Y4EoZfzzak1F6Iy2LfoUgyl8Jpg",
    "_3",
    "img3",
    "hYcxfv8XWpTIxIwnhNj33Hl2Lq4Jpg",
    "_4",
    "img4",
    "_069SD4E4Rbd50L3X97XsgTvpcJpg",
    "_5",
    "img5",
    "vk7E0Slt7OvlQa7QVqyREh2TxqcJpg",
    "ratingDetails",
    "ratingInfo",
    "ratingScore",
    "container",
    "starsContainer",
    "svg",
    "ratingText",
    "container2",
    "headerHeroSection4",
    "headerHeroSection3",
    "sectionCards3",
    "container49",
    "patternGrid",
    "htmlVideo4",
    "service05",
    "service15",
    "service25",
    "service35",
    "service45",
    "service55",
    "section"
  ],
  scrollDetector: ["scrollDetector", "newMenu"],
  newMenu: ["newMenu"],
  tickerHeader: ["tickerHeader"],
  headerHeroSection: [
    "headerHeroSection",
    "loved",
    "variant1",
    "_1",
    "img",
    "e9Q1LJl0QxOyx3A5ZmM8Jeght0YJpg",
    "_2",
    "img2",
    "tq5Y4EoZfzzak1F6Iy2LfoUgyl8Jpg",
    "_3",
    "img3",
    "hYcxfv8XWpTIxIwnhNj33Hl2Lq4Jpg",
    "_4",
    "img4",
    "_069SD4E4Rbd50L3X97XsgTvpcJpg",
    "_5",
    "img5",
    "vk7E0Slt7OvlQa7QVqyREh2TxqcJpg",
    "ratingDetails",
    "ratingInfo",
    "ratingScore",
    "container",
    "starsContainer",
    "svg",
    "ratingText",
    "container2"
  ],
  loved: [
    "loved",
    "variant1",
    "_1",
    "img",
    "e9Q1LJl0QxOyx3A5ZmM8Jeght0YJpg",
    "_2",
    "img2",
    "tq5Y4EoZfzzak1F6Iy2LfoUgyl8Jpg",
    "_3",
    "img3",
    "hYcxfv8XWpTIxIwnhNj33Hl2Lq4Jpg",
    "_4",
    "img4",
    "_069SD4E4Rbd50L3X97XsgTvpcJpg",
    "_5",
    "img5",
    "vk7E0Slt7OvlQa7QVqyREh2TxqcJpg",
    "ratingDetails",
    "ratingInfo",
    "ratingScore",
    "container",
    "starsContainer",
    "svg",
    "ratingText",
    "container2"
  ],
  variant1: [
    "variant1",
    "_1",
    "img",
    "e9Q1LJl0QxOyx3A5ZmM8Jeght0YJpg",
    "_2",
    "img2",
    "tq5Y4EoZfzzak1F6Iy2LfoUgyl8Jpg",
    "_3",
    "img3",
    "hYcxfv8XWpTIxIwnhNj33Hl2Lq4Jpg",
    "_4",
    "img4",
    "_069SD4E4Rbd50L3X97XsgTvpcJpg",
    "_5",
    "img5",
    "vk7E0Slt7OvlQa7QVqyREh2TxqcJpg",
    "ratingDetails",
    "ratingInfo",
    "ratingScore",
    "container",
    "starsContainer",
    "svg",
    "ratingText",
    "container2"
  ],
  _1: ["_1", "img", "e9Q1LJl0QxOyx3A5ZmM8Jeght0YJpg"],
  img: ["img", "e9Q1LJl0QxOyx3A5ZmM8Jeght0YJpg"],
  e9Q1LJl0QxOyx3A5ZmM8Jeght0YJpg: ["e9Q1LJl0QxOyx3A5ZmM8Jeght0YJpg"],
  _2: ["_2", "img2", "tq5Y4EoZfzzak1F6Iy2LfoUgyl8Jpg"],
  img2: ["img2", "tq5Y4EoZfzzak1F6Iy2LfoUgyl8Jpg"],
  tq5Y4EoZfzzak1F6Iy2LfoUgyl8Jpg: ["tq5Y4EoZfzzak1F6Iy2LfoUgyl8Jpg"],
  _3: ["_3", "img3", "hYcxfv8XWpTIxIwnhNj33Hl2Lq4Jpg"],
  img3: ["img3", "hYcxfv8XWpTIxIwnhNj33Hl2Lq4Jpg"],
  hYcxfv8XWpTIxIwnhNj33Hl2Lq4Jpg: ["hYcxfv8XWpTIxIwnhNj33Hl2Lq4Jpg"],
  _4: ["_4", "img4", "_069SD4E4Rbd50L3X97XsgTvpcJpg"],
  img4: ["img4", "_069SD4E4Rbd50L3X97XsgTvpcJpg"],
  _069SD4E4Rbd50L3X97XsgTvpcJpg: ["_069SD4E4Rbd50L3X97XsgTvpcJpg"],
  _5: ["_5", "img5", "vk7E0Slt7OvlQa7QVqyREh2TxqcJpg"],
  img5: ["img5", "vk7E0Slt7OvlQa7QVqyREh2TxqcJpg"],
  vk7E0Slt7OvlQa7QVqyREh2TxqcJpg: ["vk7E0Slt7OvlQa7QVqyREh2TxqcJpg"],
  ratingDetails: [
    "ratingDetails",
    "ratingInfo",
    "ratingScore",
    "container",
    "starsContainer",
    "svg",
    "ratingText",
    "container2"
  ],
  ratingInfo: [
    "ratingInfo",
    "ratingScore",
    "container",
    "starsContainer",
    "svg"
  ],
  ratingScore: ["ratingScore", "container"],
  container: ["container"],
  starsContainer: ["starsContainer", "svg"],
  svg: ["svg"],
  ratingText: ["ratingText", "container2"],
  container2: ["container2"],
  headerHeroSection4: ["headerHeroSection4"],
  headerHeroSection3: ["headerHeroSection3"],
  sectionCards3: [
    "sectionCards3",
    "container49",
    "patternGrid",
    "htmlVideo4",
    "service05",
    "service15",
    "service25",
    "service35",
    "service45",
    "service55"
  ],
  container49: [
    "container49",
    "patternGrid",
    "htmlVideo4",
    "service05",
    "service15",
    "service25",
    "service35",
    "service45",
    "service55"
  ],
  patternGrid: [
    "patternGrid",
    "htmlVideo4",
    "service05",
    "service15",
    "service25",
    "service35",
    "service45",
    "service55"
  ],
  htmlVideo4: ["htmlVideo4"],
  service05: ["service05"],
  service15: ["service15"],
  service25: ["service25"],
  service35: ["service35"],
  service45: ["service45"],
  service55: ["service55"],
  section: ["section"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  smoothScroll: typeof SmoothScroll;
  scrollDetector: typeof ScrollDetector;
  newMenu: typeof NewMenu;
  tickerHeader: typeof TickerHeader;
  headerHeroSection: "div";
  loved: "div";
  variant1: "div";
  _1: "div";
  img: "div";
  e9Q1LJl0QxOyx3A5ZmM8Jeght0YJpg: "div";
  _2: "div";
  img2: "div";
  tq5Y4EoZfzzak1F6Iy2LfoUgyl8Jpg: "div";
  _3: "div";
  img3: "div";
  hYcxfv8XWpTIxIwnhNj33Hl2Lq4Jpg: "div";
  _4: "div";
  img4: "div";
  _069SD4E4Rbd50L3X97XsgTvpcJpg: "div";
  _5: "div";
  img5: "div";
  vk7E0Slt7OvlQa7QVqyREh2TxqcJpg: "div";
  ratingDetails: "div";
  ratingInfo: "div";
  ratingScore: "div";
  container: "div";
  starsContainer: "div";
  svg: "div";
  ratingText: "div";
  container2: "div";
  headerHeroSection4: "div";
  headerHeroSection3: "div";
  sectionCards3: "div";
  container49: "div";
  patternGrid: typeof PatternGrid;
  htmlVideo4: typeof Video;
  service05: "div";
  service15: "div";
  service25: "div";
  service35: "div";
  service45: "div";
  service55: "div";
  section: typeof Section;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicWorks__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicWorks__VariantsArgs;
    args?: PlasmicWorks__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicWorks__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicWorks__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicWorks__ArgProps,
          internalVariantPropNames: PlasmicWorks__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicWorks__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicWorks";
  } else {
    func.displayName = `PlasmicWorks.${nodeName}`;
  }
  return func;
}

function withUsePlasmicAuth<P extends object>(
  WrappedComponent: React.ComponentType<P>
) {
  const WithUsePlasmicAuthComponent: React.FC<P> = props => {
    const dataSourceCtx = usePlasmicDataSourceContext() ?? {};
    const { isUserLoading, user, token } = plasmicAuth.usePlasmicAuth({
      appId: "bLa1shfC4noziDsvmxjKJF"
    });

    return (
      <PlasmicDataSourceContextProvider__
        value={{
          ...dataSourceCtx,
          isUserLoading,
          userAuthToken: token,
          user
        }}
      >
        <WrappedComponent {...props} />
      </PlasmicDataSourceContextProvider__>
    );
  };
  return WithUsePlasmicAuthComponent;
}

export const PlasmicWorks = Object.assign(
  // Top-level PlasmicWorks renders the root element
  withUsePlasmicAuth(makeNodeComponent("root")),
  {
    // Helper components rendering sub-elements
    smoothScroll: makeNodeComponent("smoothScroll"),
    scrollDetector: makeNodeComponent("scrollDetector"),
    newMenu: makeNodeComponent("newMenu"),
    tickerHeader: makeNodeComponent("tickerHeader"),
    headerHeroSection: makeNodeComponent("headerHeroSection"),
    loved: makeNodeComponent("loved"),
    variant1: makeNodeComponent("variant1"),
    _1: makeNodeComponent("_1"),
    img: makeNodeComponent("img"),
    e9Q1LJl0QxOyx3A5ZmM8Jeght0YJpg: makeNodeComponent(
      "e9Q1LJl0QxOyx3A5ZmM8Jeght0YJpg"
    ),
    _2: makeNodeComponent("_2"),
    img2: makeNodeComponent("img2"),
    tq5Y4EoZfzzak1F6Iy2LfoUgyl8Jpg: makeNodeComponent(
      "tq5Y4EoZfzzak1F6Iy2LfoUgyl8Jpg"
    ),
    _3: makeNodeComponent("_3"),
    img3: makeNodeComponent("img3"),
    hYcxfv8XWpTIxIwnhNj33Hl2Lq4Jpg: makeNodeComponent(
      "hYcxfv8XWpTIxIwnhNj33Hl2Lq4Jpg"
    ),
    _4: makeNodeComponent("_4"),
    img4: makeNodeComponent("img4"),
    _069SD4E4Rbd50L3X97XsgTvpcJpg: makeNodeComponent(
      "_069SD4E4Rbd50L3X97XsgTvpcJpg"
    ),
    _5: makeNodeComponent("_5"),
    img5: makeNodeComponent("img5"),
    vk7E0Slt7OvlQa7QVqyREh2TxqcJpg: makeNodeComponent(
      "vk7E0Slt7OvlQa7QVqyREh2TxqcJpg"
    ),
    ratingDetails: makeNodeComponent("ratingDetails"),
    ratingInfo: makeNodeComponent("ratingInfo"),
    ratingScore: makeNodeComponent("ratingScore"),
    container: makeNodeComponent("container"),
    starsContainer: makeNodeComponent("starsContainer"),
    svg: makeNodeComponent("svg"),
    ratingText: makeNodeComponent("ratingText"),
    container2: makeNodeComponent("container2"),
    headerHeroSection4: makeNodeComponent("headerHeroSection4"),
    headerHeroSection3: makeNodeComponent("headerHeroSection3"),
    sectionCards3: makeNodeComponent("sectionCards3"),
    container49: makeNodeComponent("container49"),
    patternGrid: makeNodeComponent("patternGrid"),
    htmlVideo4: makeNodeComponent("htmlVideo4"),
    service05: makeNodeComponent("service05"),
    service15: makeNodeComponent("service15"),
    service25: makeNodeComponent("service25"),
    service35: makeNodeComponent("service35"),
    service45: makeNodeComponent("service45"),
    service55: makeNodeComponent("service55"),
    section: makeNodeComponent("section"),

    // Metadata about props expected for PlasmicWorks
    internalVariantProps: PlasmicWorks__VariantProps,
    internalArgProps: PlasmicWorks__ArgProps,

    pageMetadata: generateDynamicMetadata(wrapQueriesWithLoadingProxy({}), {
      pagePath: "/new-page",
      searchParams: {},
      params: {}
    })
  }
);

export default PlasmicWorks;
/* prettier-ignore-end */
