/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: bLa1shfC4noziDsvmxjKJF
// Component: u1Kyfwr4MSZG

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { HoverController } from "../../HoverController"; // plasmic-import: NVKDfXP9Roz4/codeComponent
import { Video } from "@plasmicpkgs/plasmic-basic-components";
import { Fetcher } from "@plasmicapp/react-web/lib/data-sources";
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: bLa1shfC4noziDsvmxjKJF/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: bLa1shfC4noziDsvmxjKJF/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: bLa1shfC4noziDsvmxjKJF/projectcss
import sty from "./PlasmicTemplateCard.module.css"; // plasmic-import: u1Kyfwr4MSZG/css

createPlasmicElementProxy;

export type PlasmicTemplateCard__VariantMembers = {
  project1: "project1";
};
export type PlasmicTemplateCard__VariantsArgs = {
  project1?: SingleBooleanChoiceArg<"project1">;
};
type VariantPropType = keyof PlasmicTemplateCard__VariantsArgs;
export const PlasmicTemplateCard__VariantProps = new Array<VariantPropType>(
  "project1"
);

export type PlasmicTemplateCard__ArgsType = {
  video?: string;
  videoCondition?: boolean;
  imageCondition?: boolean;
  link?: string;
  title?: string;
  softwareContainerSoftware2?: React.ReactNode;
  image2?: string;
};
type ArgPropType = keyof PlasmicTemplateCard__ArgsType;
export const PlasmicTemplateCard__ArgProps = new Array<ArgPropType>(
  "video",
  "videoCondition",
  "imageCondition",
  "link",
  "title",
  "softwareContainerSoftware2",
  "image2"
);

export type PlasmicTemplateCard__OverridesType = {
  linkDesktopColored?: Flex__<"div">;
  image?: Flex__<"div">;
  border?: Flex__<"div">;
  screws?: Flex__<"div">;
  _1?: Flex__<"div">;
  _2?: Flex__<"div">;
  _3?: Flex__<"div">;
  _4?: Flex__<"div">;
  overlay2?: Flex__<"div">;
  link?: Flex__<"a"> & Partial<LinkProps>;
  hoverController?: Flex__<typeof HoverController>;
  htmlVideo?: Flex__<typeof Video>;
  bottom?: Flex__<"div">;
  top2?: Flex__<"div">;
  templateName?: Flex__<"div">;
  text?: Flex__<"div">;
  container10?: Flex__<"div">;
};

export interface DefaultTemplateCardProps {
  video?: string;
  videoCondition?: boolean;
  imageCondition?: boolean;
  link?: string;
  title?: string;
  softwareContainerSoftware2?: React.ReactNode;
  image2?: string;
  project1?: SingleBooleanChoiceArg<"project1">;
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicTemplateCard__RenderFunc(props: {
  variants: PlasmicTemplateCard__VariantsArgs;
  args: PlasmicTemplateCard__ArgsType;
  overrides: PlasmicTemplateCard__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {
          video:
            "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.webm",
          videoCondition: false,
          imageCondition: true,
          image2:
            "https://framerusercontent.com/images/kPjJi3SaQayZ8Z3vprpR1gKZ47U.webp"
        },
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = useCurrentUser?.() || {};

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "project1",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) =>
          (() => {
            try {
              return $state.hover2;
            } catch (e) {
              if (
                e instanceof TypeError ||
                e?.plasmicType === "PlasmicUndefinedDataError"
              ) {
                return undefined;
              }
              throw e;
            }
          })() ?? $props.project1
      },
      {
        path: "hover2",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) =>
          (() => {
            try {
              return false;
            } catch (e) {
              if (
                e instanceof TypeError ||
                e?.plasmicType === "PlasmicUndefinedDataError"
              ) {
                return false;
              }
              throw e;
            }
          })()
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $q: {},
    $refs
  });

  const styleTokensClassNames = _useStyleTokens();

  return (
    <div
      data-plasmic-name={"linkDesktopColored"}
      data-plasmic-override={overrides.linkDesktopColored}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        styleTokensClassNames,
        sty.linkDesktopColored,
        {
          [sty.linkDesktopColoredproject1]: hasVariant(
            $state,
            "project1",
            "project1"
          )
        }
      )}
    >
      <div
        data-plasmic-name={"image"}
        data-plasmic-override={overrides.image}
        className={classNames(projectcss.all, sty.image)}
      >
        <div
          data-plasmic-name={"border"}
          data-plasmic-override={overrides.border}
          className={classNames(projectcss.all, sty.border)}
        />

        <div
          data-plasmic-name={"screws"}
          data-plasmic-override={overrides.screws}
          className={classNames(projectcss.all, sty.screws)}
        >
          <div
            data-plasmic-name={"_1"}
            data-plasmic-override={overrides._1}
            className={classNames(projectcss.all, sty._1)}
          />

          <div
            data-plasmic-name={"_2"}
            data-plasmic-override={overrides._2}
            className={classNames(projectcss.all, sty._2)}
          />

          <div
            data-plasmic-name={"_3"}
            data-plasmic-override={overrides._3}
            className={classNames(projectcss.all, sty._3)}
          />

          <div
            data-plasmic-name={"_4"}
            data-plasmic-override={overrides._4}
            className={classNames(projectcss.all, sty._4)}
          />
        </div>
        <div
          data-plasmic-name={"overlay2"}
          data-plasmic-override={overrides.overlay2}
          className={classNames(projectcss.all, sty.overlay2, {
            [sty.overlay2project1]: hasVariant($state, "project1", "project1")
          })}
        >
          <PlasmicLink__
            data-plasmic-name={"link"}
            data-plasmic-override={overrides.link}
            className={classNames(projectcss.all, projectcss.a, sty.link, {
              [sty.linkproject1]: hasVariant($state, "project1", "project1")
            })}
            component={Link}
            href={args.link}
            legacyBehavior={false}
            platform={"nextjs"}
          >
            <HoverController
              data-plasmic-name={"hoverController"}
              data-plasmic-override={overrides.hoverController}
              className={classNames("__wab_instance", sty.hoverController, {
                [sty.hoverControllerproject1]: hasVariant(
                  $state,
                  "project1",
                  "project1"
                )
              })}
              onHoverChange={async isHovered => {
                const $steps = {};

                $steps["updateHover2"] = true
                  ? (() => {
                      const actionArgs = {
                        variable: {
                          objRoot: $state,
                          variablePath: ["hover2"]
                        },
                        operation: 0,
                        value: isHovered
                      };
                      return (({
                        variable,
                        value,
                        startIndex,
                        deleteCount
                      }) => {
                        if (!variable) {
                          return;
                        }
                        const { objRoot, variablePath } = variable;

                        $stateSet(objRoot, variablePath, value);
                        return value;
                      })?.apply(null, [actionArgs]);
                    })()
                  : undefined;
                if (
                  $steps["updateHover2"] != null &&
                  typeof $steps["updateHover2"] === "object" &&
                  typeof $steps["updateHover2"].then === "function"
                ) {
                  $steps["updateHover2"] = await $steps["updateHover2"];
                }
              }}
              trigger={
                <DataCtxReader__>
                  {$ctx => (
                    <React.Fragment>
                      {(() => {
                        try {
                          return $props.videoCondition;
                        } catch (e) {
                          if (
                            e instanceof TypeError ||
                            e?.plasmicType === "PlasmicUndefinedDataError"
                          ) {
                            return true;
                          }
                          throw e;
                        }
                      })() ? (
                        <Video
                          data-plasmic-name={"htmlVideo"}
                          data-plasmic-override={overrides.htmlVideo}
                          autoPlay={true}
                          className={classNames(
                            "__wab_instance",
                            sty.htmlVideo,
                            {
                              [sty.htmlVideoproject1]: hasVariant(
                                $state,
                                "project1",
                                "project1"
                              )
                            }
                          )}
                          controls={false}
                          loop={true}
                          muted={true}
                          ref={ref => {
                            $refs["htmlVideo"] = ref;
                          }}
                          src={args.video}
                        />
                      ) : null}
                      {(() => {
                        try {
                          return $props.imageCondition;
                        } catch (e) {
                          if (
                            e instanceof TypeError ||
                            e?.plasmicType === "PlasmicUndefinedDataError"
                          ) {
                            return true;
                          }
                          throw e;
                        }
                      })() ? (
                        <PlasmicImg__
                          alt={""}
                          className={classNames(sty.img__czgbX, {
                            [sty.imgproject1__czgbXz20FZ]: hasVariant(
                              $state,
                              "project1",
                              "project1"
                            )
                          })}
                          displayHeight={"100%"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"100%"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"100%"}
                          loading={"lazy"}
                          src={(() => {
                            try {
                              return $props.image2;
                            } catch (e) {
                              if (
                                e instanceof TypeError ||
                                e?.plasmicType === "PlasmicUndefinedDataError"
                              ) {
                                return undefined;
                              }
                              throw e;
                            }
                          })()}
                        />
                      ) : null}
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__qDo,
                          {
                            [sty.freeBoxproject1__qDOz20FZ]: hasVariant(
                              $state,
                              "project1",
                              "project1"
                            )
                          }
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__hrNtM,
                            {
                              [sty.freeBoxproject1__hrNtMz20FZ]: hasVariant(
                                $state,
                                "project1",
                                "project1"
                              )
                            }
                          )}
                        >
                          <PlasmicImg__
                            alt={""}
                            className={classNames(sty.img__yMKni, {
                              [sty.imgproject1__yMKniz20FZ]: hasVariant(
                                $state,
                                "project1",
                                "project1"
                              )
                            })}
                            displayHeight={
                              hasVariant($state, "project1", "project1")
                                ? "auto"
                                : "auto"
                            }
                            displayMaxHeight={"none"}
                            displayMaxWidth={"100%"}
                            displayMinHeight={"0"}
                            displayMinWidth={"0"}
                            displayWidth={
                              hasVariant($state, "project1", "project1")
                                ? "100%"
                                : "100%"
                            }
                            loading={"lazy"}
                            src={(() => {
                              try {
                                return $props.image2;
                              } catch (e) {
                                if (
                                  e instanceof TypeError ||
                                  e?.plasmicType === "PlasmicUndefinedDataError"
                                ) {
                                  return undefined;
                                }
                                throw e;
                              }
                            })()}
                          />
                        </div>
                      </div>
                    </React.Fragment>
                  )}
                </DataCtxReader__>
              }
            />
          </PlasmicLink__>
        </div>
      </div>
      <div
        data-plasmic-name={"bottom"}
        data-plasmic-override={overrides.bottom}
        className={classNames(projectcss.all, sty.bottom, {
          [sty.bottomproject1]: hasVariant($state, "project1", "project1")
        })}
      >
        <div
          data-plasmic-name={"top2"}
          data-plasmic-override={overrides.top2}
          className={classNames(projectcss.all, sty.top2)}
        >
          <div
            data-plasmic-name={"templateName"}
            data-plasmic-override={overrides.templateName}
            className={classNames(projectcss.all, sty.templateName)}
          >
            <div
              data-plasmic-name={"text"}
              data-plasmic-override={overrides.text}
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text
              )}
            >
              <React.Fragment>
                {(() => {
                  try {
                    return $props.title;
                  } catch (e) {
                    if (
                      e instanceof TypeError ||
                      e?.plasmicType === "PlasmicUndefinedDataError"
                    ) {
                      return "Vectura";
                    }
                    throw e;
                  }
                })()}
              </React.Fragment>
            </div>
          </div>
        </div>
        <div
          data-plasmic-name={"container10"}
          data-plasmic-override={overrides.container10}
          className={classNames(projectcss.all, sty.container10)}
        >
          {renderPlasmicSlot({
            defaultContents: (
              <div className={classNames(projectcss.all, sty.freeBox__qrLsn)}>
                <div className={classNames(projectcss.all, sty.freeBox__zl0Sx)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__bEoHv
                    )}
                  >
                    {"Framer"}
                  </div>
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__m0QFu)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__bfvur
                    )}
                  >
                    {"Framer"}
                  </div>
                </div>
                <div
                  className={classNames(projectcss.all, sty.freeBox___3HTu0)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__idsCo
                    )}
                  >
                    {"Framer"}
                  </div>
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__mdfGw)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__xJhCh
                    )}
                  >
                    {"Framer"}
                  </div>
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__yOgF)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__l4V4Y
                    )}
                  >
                    {"Framer"}
                  </div>
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__hnjqN)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__lP0Jn
                    )}
                  >
                    {"Framer"}
                  </div>
                </div>
              </div>
            ),
            value: args.softwareContainerSoftware2
          })}
        </div>
      </div>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  linkDesktopColored: [
    "linkDesktopColored",
    "image",
    "border",
    "screws",
    "_1",
    "_2",
    "_3",
    "_4",
    "overlay2",
    "link",
    "hoverController",
    "htmlVideo",
    "bottom",
    "top2",
    "templateName",
    "text",
    "container10"
  ],
  image: [
    "image",
    "border",
    "screws",
    "_1",
    "_2",
    "_3",
    "_4",
    "overlay2",
    "link",
    "hoverController",
    "htmlVideo"
  ],
  border: ["border"],
  screws: ["screws", "_1", "_2", "_3", "_4"],
  _1: ["_1"],
  _2: ["_2"],
  _3: ["_3"],
  _4: ["_4"],
  overlay2: ["overlay2", "link", "hoverController", "htmlVideo"],
  link: ["link", "hoverController", "htmlVideo"],
  hoverController: ["hoverController", "htmlVideo"],
  htmlVideo: ["htmlVideo"],
  bottom: ["bottom", "top2", "templateName", "text", "container10"],
  top2: ["top2", "templateName", "text"],
  templateName: ["templateName", "text"],
  text: ["text"],
  container10: ["container10"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  linkDesktopColored: "div";
  image: "div";
  border: "div";
  screws: "div";
  _1: "div";
  _2: "div";
  _3: "div";
  _4: "div";
  overlay2: "div";
  link: "a";
  hoverController: typeof HoverController;
  htmlVideo: typeof Video;
  bottom: "div";
  top2: "div";
  templateName: "div";
  text: "div";
  container10: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicTemplateCard__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicTemplateCard__VariantsArgs;
    args?: PlasmicTemplateCard__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicTemplateCard__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicTemplateCard__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicTemplateCard__ArgProps,
          internalVariantPropNames: PlasmicTemplateCard__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicTemplateCard__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "linkDesktopColored") {
    func.displayName = "PlasmicTemplateCard";
  } else {
    func.displayName = `PlasmicTemplateCard.${nodeName}`;
  }
  return func;
}

export const PlasmicTemplateCard = Object.assign(
  // Top-level PlasmicTemplateCard renders the root element
  makeNodeComponent("linkDesktopColored"),
  {
    // Helper components rendering sub-elements
    image: makeNodeComponent("image"),
    border: makeNodeComponent("border"),
    screws: makeNodeComponent("screws"),
    _1: makeNodeComponent("_1"),
    _2: makeNodeComponent("_2"),
    _3: makeNodeComponent("_3"),
    _4: makeNodeComponent("_4"),
    overlay2: makeNodeComponent("overlay2"),
    link: makeNodeComponent("link"),
    hoverController: makeNodeComponent("hoverController"),
    htmlVideo: makeNodeComponent("htmlVideo"),
    bottom: makeNodeComponent("bottom"),
    top2: makeNodeComponent("top2"),
    templateName: makeNodeComponent("templateName"),
    text: makeNodeComponent("text"),
    container10: makeNodeComponent("container10"),

    // Metadata about props expected for PlasmicTemplateCard
    internalVariantProps: PlasmicTemplateCard__VariantProps,
    internalArgProps: PlasmicTemplateCard__ArgProps
  }
);

export default PlasmicTemplateCard;
/* prettier-ignore-end */
