/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: bLa1shfC4noziDsvmxjKJF
// Component: oLdNG6yB_GWb

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { Fetcher } from "@plasmicapp/react-web/lib/data-sources";
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: bLa1shfC4noziDsvmxjKJF/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: bLa1shfC4noziDsvmxjKJF/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: bLa1shfC4noziDsvmxjKJF/projectcss
import sty from "./PlasmicMegaMenu.module.css"; // plasmic-import: oLdNG6yB_GWb/css

import IconIcon from "./icons/PlasmicIcon__Icon"; // plasmic-import: MpGNbkOGJDen/icon
import Component1Icon from "./icons/PlasmicIcon__Component1"; // plasmic-import: Y8Z0b7C0gH0B/icon
import Component2Icon from "./icons/PlasmicIcon__Component2"; // plasmic-import: B-PEmF-FKsY-/icon
import Component3Icon from "./icons/PlasmicIcon__Component3"; // plasmic-import: FDz_Lh9IuoyH/icon
import Component4Icon from "./icons/PlasmicIcon__Component4"; // plasmic-import: La3DKQmXAFqc/icon

createPlasmicElementProxy;

export type PlasmicMegaMenu__VariantMembers = {
  showIcon: "showIcon";
};
export type PlasmicMegaMenu__VariantsArgs = {
  showIcon?: SingleBooleanChoiceArg<"showIcon">;
};
type VariantPropType = keyof PlasmicMegaMenu__VariantsArgs;
export const PlasmicMegaMenu__VariantProps = new Array<VariantPropType>(
  "showIcon"
);

export type PlasmicMegaMenu__ArgsType = {};
type ArgPropType = keyof PlasmicMegaMenu__ArgsType;
export const PlasmicMegaMenu__ArgProps = new Array<ArgPropType>();

export type PlasmicMegaMenu__OverridesType = {
  menu?: Flex__<"div">;
  container?: Flex__<"div">;
  link?: Flex__<"div">;
  container2?: Flex__<"div">;
  background?: Flex__<"div">;
  img?: Flex__<typeof PlasmicImg__>;
  nav?: Flex__<"div">;
  link2?: Flex__<"div">;
  container5?: Flex__<"div">;
  link3?: Flex__<"div">;
  container6?: Flex__<"div">;
  link4?: Flex__<"div">;
  container7?: Flex__<"div">;
  horizontalBorder?: Flex__<"div">;
  link5?: Flex__<"div">;
  container8?: Flex__<"div">;
};

export interface DefaultMegaMenuProps {
  showIcon?: SingleBooleanChoiceArg<"showIcon">;
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicMegaMenu__RenderFunc(props: {
  variants: PlasmicMegaMenu__VariantsArgs;
  args: PlasmicMegaMenu__ArgsType;
  overrides: PlasmicMegaMenu__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = useCurrentUser?.() || {};

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "isHovered",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => false
      },
      {
        path: "showIcon",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) =>
          (() => {
            try {
              return $state.isHovered;
            } catch (e) {
              if (
                e instanceof TypeError ||
                e?.plasmicType === "PlasmicUndefinedDataError"
              ) {
                return undefined;
              }
              throw e;
            }
          })() ?? $props.showIcon
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $q: {},
    $refs
  });

  const styleTokensClassNames = _useStyleTokens();

  return (
    <div
      data-plasmic-name={"menu"}
      data-plasmic-override={overrides.menu}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        styleTokensClassNames,
        sty.menu,
        { [sty.menushowIcon]: hasVariant($state, "showIcon", "showIcon") }
      )}
      onMouseEnter={async event => {
        const $steps = {};

        $steps["updateIsHovered"] = true
          ? (() => {
              const actionArgs = {
                variable: {
                  objRoot: $state,
                  variablePath: ["isHovered"]
                },
                operation: 0,
                value: true
              };
              return (({ variable, value, startIndex, deleteCount }) => {
                if (!variable) {
                  return;
                }
                const { objRoot, variablePath } = variable;

                $stateSet(objRoot, variablePath, value);
                return value;
              })?.apply(null, [actionArgs]);
            })()
          : undefined;
        if (
          $steps["updateIsHovered"] != null &&
          typeof $steps["updateIsHovered"] === "object" &&
          typeof $steps["updateIsHovered"].then === "function"
        ) {
          $steps["updateIsHovered"] = await $steps["updateIsHovered"];
        }
      }}
      onMouseLeave={async event => {
        const $steps = {};

        $steps["updateIsHovered"] = true
          ? (() => {
              const actionArgs = {
                variable: {
                  objRoot: $state,
                  variablePath: ["isHovered"]
                },
                operation: 0,
                value: false
              };
              return (({ variable, value, startIndex, deleteCount }) => {
                if (!variable) {
                  return;
                }
                const { objRoot, variablePath } = variable;

                $stateSet(objRoot, variablePath, value);
                return value;
              })?.apply(null, [actionArgs]);
            })()
          : undefined;
        if (
          $steps["updateIsHovered"] != null &&
          typeof $steps["updateIsHovered"] === "object" &&
          typeof $steps["updateIsHovered"].then === "function"
        ) {
          $steps["updateIsHovered"] = await $steps["updateIsHovered"];
        }
      }}
    >
      <div
        data-plasmic-name={"container"}
        data-plasmic-override={overrides.container}
        className={classNames(projectcss.all, sty.container)}
      >
        <div
          data-plasmic-name={"link"}
          data-plasmic-override={overrides.link}
          className={classNames(projectcss.all, sty.link, {
            [sty.linkshowIcon]: hasVariant($state, "showIcon", "showIcon")
          })}
        >
          <div
            data-plasmic-name={"container2"}
            data-plasmic-override={overrides.container2}
            className={classNames(projectcss.all, sty.container2)}
          >
            <div
              data-plasmic-name={"background"}
              data-plasmic-override={overrides.background}
              className={classNames(projectcss.all, sty.background)}
            >
              <PlasmicImg__
                data-plasmic-name={"img"}
                data-plasmic-override={overrides.img}
                alt={""}
                className={classNames(sty.img)}
                displayHeight={"auto"}
                displayMaxHeight={"none"}
                displayMaxWidth={"100%"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"32px"}
                loading={"lazy"}
                src={{
                  src: "/plasmic/son_vo/images/image.svg",
                  fullWidth: 53,
                  fullHeight: 60,
                  aspectRatio: undefined
                }}
              />

              <IconIcon
                className={classNames(projectcss.all, sty.svg___8T6Po, {
                  [sty.svgshowIcon___8T6Po1MvH]: hasVariant(
                    $state,
                    "showIcon",
                    "showIcon"
                  )
                })}
                role={"img"}
              />
            </div>
          </div>
        </div>
        <div
          data-plasmic-name={"nav"}
          data-plasmic-override={overrides.nav}
          className={classNames(projectcss.all, sty.nav, {
            [sty.navshowIcon]: hasVariant($state, "showIcon", "showIcon")
          })}
        >
          <div
            data-plasmic-name={"link2"}
            data-plasmic-override={overrides.link2}
            className={classNames(projectcss.all, sty.link2, {
              [sty.link2showIcon]: hasVariant($state, "showIcon", "showIcon")
            })}
          >
            <Component1Icon
              className={classNames(projectcss.all, sty.svg___44Nz8)}
              role={"img"}
            />

            <div
              data-plasmic-name={"container5"}
              data-plasmic-override={overrides.container5}
              className={classNames(projectcss.all, sty.container5, {
                [sty.container5showIcon]: hasVariant(
                  $state,
                  "showIcon",
                  "showIcon"
                )
              })}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__f8VqL,
                  {
                    [sty.textshowIcon__f8VqL1MvH]: hasVariant(
                      $state,
                      "showIcon",
                      "showIcon"
                    )
                  }
                )}
              >
                {"Home"}
              </div>
            </div>
          </div>
          <div
            data-plasmic-name={"link3"}
            data-plasmic-override={overrides.link3}
            className={classNames(projectcss.all, sty.link3, {
              [sty.link3showIcon]: hasVariant($state, "showIcon", "showIcon")
            })}
          >
            <Component2Icon
              className={classNames(projectcss.all, sty.svg__bUrFv, {
                [sty.svgshowIcon__bUrFv1MvH]: hasVariant(
                  $state,
                  "showIcon",
                  "showIcon"
                )
              })}
              role={"img"}
            />

            <div
              data-plasmic-name={"container6"}
              data-plasmic-override={overrides.container6}
              className={classNames(projectcss.all, sty.container6, {
                [sty.container6showIcon]: hasVariant(
                  $state,
                  "showIcon",
                  "showIcon"
                )
              })}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__klqWl,
                  {
                    [sty.textshowIcon__klqWl1MvH]: hasVariant(
                      $state,
                      "showIcon",
                      "showIcon"
                    )
                  }
                )}
              >
                {"Templates"}
              </div>
            </div>
          </div>
          <div
            data-plasmic-name={"link4"}
            data-plasmic-override={overrides.link4}
            className={classNames(projectcss.all, sty.link4, {
              [sty.link4showIcon]: hasVariant($state, "showIcon", "showIcon")
            })}
          >
            <Component3Icon
              className={classNames(projectcss.all, sty.svg__rPbun)}
              role={"img"}
            />

            <div
              data-plasmic-name={"container7"}
              data-plasmic-override={overrides.container7}
              className={classNames(projectcss.all, sty.container7, {
                [sty.container7showIcon]: hasVariant(
                  $state,
                  "showIcon",
                  "showIcon"
                )
              })}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___0TPz9,
                  {
                    [sty.textshowIcon___0TPz91MvH]: hasVariant(
                      $state,
                      "showIcon",
                      "showIcon"
                    )
                  }
                )}
              >
                {"Blog"}
              </div>
            </div>
          </div>
        </div>
        <div
          data-plasmic-name={"horizontalBorder"}
          data-plasmic-override={overrides.horizontalBorder}
          className={classNames(projectcss.all, sty.horizontalBorder)}
        >
          <div
            data-plasmic-name={"link5"}
            data-plasmic-override={overrides.link5}
            className={classNames(projectcss.all, sty.link5, {
              [sty.link5showIcon]: hasVariant($state, "showIcon", "showIcon")
            })}
          >
            <Component4Icon
              className={classNames(projectcss.all, sty.svg__iB26M)}
              role={"img"}
            />

            <div
              data-plasmic-name={"container8"}
              data-plasmic-override={overrides.container8}
              className={classNames(projectcss.all, sty.container8, {
                [sty.container8showIcon]: hasVariant(
                  $state,
                  "showIcon",
                  "showIcon"
                )
              })}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___1Zjt9
                )}
              >
                {"Contact"}
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  menu: [
    "menu",
    "container",
    "link",
    "container2",
    "background",
    "img",
    "nav",
    "link2",
    "container5",
    "link3",
    "container6",
    "link4",
    "container7",
    "horizontalBorder",
    "link5",
    "container8"
  ],
  container: [
    "container",
    "link",
    "container2",
    "background",
    "img",
    "nav",
    "link2",
    "container5",
    "link3",
    "container6",
    "link4",
    "container7",
    "horizontalBorder",
    "link5",
    "container8"
  ],
  link: ["link", "container2", "background", "img"],
  container2: ["container2", "background", "img"],
  background: ["background", "img"],
  img: ["img"],
  nav: [
    "nav",
    "link2",
    "container5",
    "link3",
    "container6",
    "link4",
    "container7"
  ],
  link2: ["link2", "container5"],
  container5: ["container5"],
  link3: ["link3", "container6"],
  container6: ["container6"],
  link4: ["link4", "container7"],
  container7: ["container7"],
  horizontalBorder: ["horizontalBorder", "link5", "container8"],
  link5: ["link5", "container8"],
  container8: ["container8"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  menu: "div";
  container: "div";
  link: "div";
  container2: "div";
  background: "div";
  img: typeof PlasmicImg__;
  nav: "div";
  link2: "div";
  container5: "div";
  link3: "div";
  container6: "div";
  link4: "div";
  container7: "div";
  horizontalBorder: "div";
  link5: "div";
  container8: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicMegaMenu__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicMegaMenu__VariantsArgs;
    args?: PlasmicMegaMenu__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicMegaMenu__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicMegaMenu__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicMegaMenu__ArgProps,
          internalVariantPropNames: PlasmicMegaMenu__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicMegaMenu__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "menu") {
    func.displayName = "PlasmicMegaMenu";
  } else {
    func.displayName = `PlasmicMegaMenu.${nodeName}`;
  }
  return func;
}

export const PlasmicMegaMenu = Object.assign(
  // Top-level PlasmicMegaMenu renders the root element
  makeNodeComponent("menu"),
  {
    // Helper components rendering sub-elements
    container: makeNodeComponent("container"),
    link: makeNodeComponent("link"),
    container2: makeNodeComponent("container2"),
    background: makeNodeComponent("background"),
    img: makeNodeComponent("img"),
    nav: makeNodeComponent("nav"),
    link2: makeNodeComponent("link2"),
    container5: makeNodeComponent("container5"),
    link3: makeNodeComponent("link3"),
    container6: makeNodeComponent("container6"),
    link4: makeNodeComponent("link4"),
    container7: makeNodeComponent("container7"),
    horizontalBorder: makeNodeComponent("horizontalBorder"),
    link5: makeNodeComponent("link5"),
    container8: makeNodeComponent("container8"),

    // Metadata about props expected for PlasmicMegaMenu
    internalVariantProps: PlasmicMegaMenu__VariantProps,
    internalArgProps: PlasmicMegaMenu__ArgProps
  }
);

export default PlasmicMegaMenu;
/* prettier-ignore-end */
