/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: bLa1shfC4noziDsvmxjKJF
// Component: fX5hEjjykD_1

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { Fetcher } from "@plasmicapp/react-web/lib/data-sources";
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: bLa1shfC4noziDsvmxjKJF/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: bLa1shfC4noziDsvmxjKJF/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import sty from "./PlasmicCardWhatAboutUs.module.css"; // plasmic-import: fX5hEjjykD_1/css

createPlasmicElementProxy;

export type PlasmicCardWhatAboutUs__VariantMembers = {
  _2: "_21" | "_3";
};
export type PlasmicCardWhatAboutUs__VariantsArgs = {
  _2?: SingleChoiceArg<"_21" | "_3">;
};
type VariantPropType = keyof PlasmicCardWhatAboutUs__VariantsArgs;
export const PlasmicCardWhatAboutUs__VariantProps = new Array<VariantPropType>(
  "_2"
);

export type PlasmicCardWhatAboutUs__ArgsType = {};
type ArgPropType = keyof PlasmicCardWhatAboutUs__ArgsType;
export const PlasmicCardWhatAboutUs__ArgProps = new Array<ArgPropType>();

export type PlasmicCardWhatAboutUs__OverridesType = {
  wrapped?: Flex__<"div">;
  freeBox?: Flex__<"div">;
  container5?: Flex__<"div">;
  imageWithFallback?: Flex__<"div">;
  container31?: Flex__<"div">;
  container4?: Flex__<"div">;
  text?: Flex__<"div">;
  paragraph?: Flex__<"div">;
  greatProductsDontJustHappenTheyreShapedB?: Flex__<"div">;
};

export interface DefaultCardWhatAboutUsProps {
  _2?: SingleChoiceArg<"_21" | "_3">;
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicCardWhatAboutUs__RenderFunc(props: {
  variants: PlasmicCardWhatAboutUs__VariantsArgs;
  args: PlasmicCardWhatAboutUs__ArgsType;
  overrides: PlasmicCardWhatAboutUs__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "isHovered",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => false
      },
      {
        path: "_2",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => $props._2
      }
    ],
    [$props, $ctx, $refs]
  );

  const currentUser = useCurrentUser?.() || {};

  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $q: {},
    $refs
  });

  const styleTokensClassNames = _useStyleTokens();

  return (
    <div
      data-plasmic-name={"wrapped"}
      data-plasmic-override={overrides.wrapped}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        "all",
        "root_reset_bLa1shfC4noziDsvmxjKJF",
        "plasmic_default_styles",
        "plasmic_mixins",
        styleTokensClassNames,
        sty.wrapped,
        {
          [sty.wrapped_2__21]: hasVariant($state, "_2", "_21"),
          [sty.wrapped_2__3]: hasVariant($state, "_2", "_3")
        }
      )}
    >
      <div
        data-plasmic-name={"freeBox"}
        data-plasmic-override={overrides.freeBox}
        className={classNames("all", sty.freeBox)}
      >
        <div
          data-plasmic-name={"container5"}
          data-plasmic-override={overrides.container5}
          className={classNames("all", sty.container5)}
        >
          <div
            data-plasmic-name={"imageWithFallback"}
            data-plasmic-override={overrides.imageWithFallback}
            className={classNames("all", sty.imageWithFallback, {
              [sty.imageWithFallback_2__21]: hasVariant($state, "_2", "_21"),
              [sty.imageWithFallback_2__3]: hasVariant($state, "_2", "_3")
            })}
          />
        </div>
        <div
          data-plasmic-name={"container31"}
          data-plasmic-override={overrides.container31}
          className={classNames("all", sty.container31)}
        >
          <div
            data-plasmic-name={"container4"}
            data-plasmic-override={overrides.container4}
            className={classNames("all", sty.container4)}
          >
            <div
              className={classNames("all", "__wab_text", sty.text___0WT5Z, {
                [sty.text_2__21___0WT5ZIWhUo]: hasVariant($state, "_2", "_21"),
                [sty.text_2__3___0WT5ZvikA]: hasVariant($state, "_2", "_3")
              })}
            >
              {hasVariant($state, "_2", "_3")
                ? "Brand strategy and identity design\r"
                : hasVariant($state, "_2", "_21")
                  ? "App and website design\r"
                  : "Product strategy and design"}
            </div>
            <div
              data-plasmic-name={"text"}
              data-plasmic-override={overrides.text}
              className={classNames("all", sty.text, {
                [sty.text_2__21]: hasVariant($state, "_2", "_21")
              })}
            >
              <div
                className={classNames("all", "__wab_text", sty.text__tg3OG, {
                  [sty.text_2__21__tg3OGiWhUo]: hasVariant($state, "_2", "_21"),
                  [sty.text_2__3__tg3OGvikA]: hasVariant($state, "_2", "_3")
                })}
              >
                {hasVariant($state, "_2", "_3")
                  ? "03"
                  : hasVariant($state, "_2", "_21")
                    ? "02"
                    : "01"}
              </div>
            </div>
          </div>
          <div
            data-plasmic-name={"paragraph"}
            data-plasmic-override={overrides.paragraph}
            className={classNames("all", sty.paragraph)}
          >
            <div
              data-plasmic-name={"greatProductsDontJustHappenTheyreShapedB"}
              data-plasmic-override={
                overrides.greatProductsDontJustHappenTheyreShapedB
              }
              className={classNames(
                "all",
                "__wab_text",
                sty.greatProductsDontJustHappenTheyreShapedB,
                {
                  [sty.greatProductsDontJustHappenTheyreShapedB_2__21]:
                    hasVariant($state, "_2", "_21"),
                  [sty.greatProductsDontJustHappenTheyreShapedB_2__3]:
                    hasVariant($state, "_2", "_3")
                }
              )}
            >
              {hasVariant($state, "_2", "_3")
                ? "Why look like someone else when you want to stand out? Together, we craft unique brand identities across touchpoints with a digital-first mindset. We bring the spark by distilling your brand DNA and getting to the root of what your users actually want."
                : hasVariant($state, "_2", "_21")
                  ? "We think outside the box to make sure your product sets itself apart and sets the bar. We build beautiful, intuitive interfaces that are compelling and consistent, powered by scalable design systems."
                  : "Great products don't just happen, they're shaped by insight. We dig into research, audits, and user testing to understand what people need, then translate those findings into smart, intuitive UX solutions where every decision has purpose."}
            </div>
          </div>
        </div>
      </div>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  wrapped: [
    "wrapped",
    "freeBox",
    "container5",
    "imageWithFallback",
    "container31",
    "container4",
    "text",
    "paragraph",
    "greatProductsDontJustHappenTheyreShapedB"
  ],
  freeBox: [
    "freeBox",
    "container5",
    "imageWithFallback",
    "container31",
    "container4",
    "text",
    "paragraph",
    "greatProductsDontJustHappenTheyreShapedB"
  ],
  container5: ["container5", "imageWithFallback"],
  imageWithFallback: ["imageWithFallback"],
  container31: [
    "container31",
    "container4",
    "text",
    "paragraph",
    "greatProductsDontJustHappenTheyreShapedB"
  ],
  container4: ["container4", "text"],
  text: ["text"],
  paragraph: ["paragraph", "greatProductsDontJustHappenTheyreShapedB"],
  greatProductsDontJustHappenTheyreShapedB: [
    "greatProductsDontJustHappenTheyreShapedB"
  ]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  wrapped: "div";
  freeBox: "div";
  container5: "div";
  imageWithFallback: "div";
  container31: "div";
  container4: "div";
  text: "div";
  paragraph: "div";
  greatProductsDontJustHappenTheyreShapedB: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicCardWhatAboutUs__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicCardWhatAboutUs__VariantsArgs;
    args?: PlasmicCardWhatAboutUs__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicCardWhatAboutUs__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicCardWhatAboutUs__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicCardWhatAboutUs__ArgProps,
          internalVariantPropNames: PlasmicCardWhatAboutUs__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicCardWhatAboutUs__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "wrapped") {
    func.displayName = "PlasmicCardWhatAboutUs";
  } else {
    func.displayName = `PlasmicCardWhatAboutUs.${nodeName}`;
  }
  return func;
}

export const PlasmicCardWhatAboutUs = Object.assign(
  // Top-level PlasmicCardWhatAboutUs renders the root element
  makeNodeComponent("wrapped"),
  {
    // Helper components rendering sub-elements
    freeBox: makeNodeComponent("freeBox"),
    container5: makeNodeComponent("container5"),
    imageWithFallback: makeNodeComponent("imageWithFallback"),
    container31: makeNodeComponent("container31"),
    container4: makeNodeComponent("container4"),
    text: makeNodeComponent("text"),
    paragraph: makeNodeComponent("paragraph"),
    greatProductsDontJustHappenTheyreShapedB: makeNodeComponent(
      "greatProductsDontJustHappenTheyreShapedB"
    ),

    // Metadata about props expected for PlasmicCardWhatAboutUs
    internalVariantProps: PlasmicCardWhatAboutUs__VariantProps,
    internalArgProps: PlasmicCardWhatAboutUs__ArgProps
  }
);

export default PlasmicCardWhatAboutUs;
/* prettier-ignore-end */
