/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: bLa1shfC4noziDsvmxjKJF
// Component: dkKX5oUPUtTr

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { HoverController } from "../../HoverController"; // plasmic-import: NVKDfXP9Roz4/codeComponent
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: bLa1shfC4noziDsvmxjKJF/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: bLa1shfC4noziDsvmxjKJF/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: bLa1shfC4noziDsvmxjKJF/projectcss
import sty from "./PlasmicCardExperience.module.css"; // plasmic-import: dkKX5oUPUtTr/css

createPlasmicElementProxy;

export type PlasmicCardExperience__VariantMembers = {
  project1: "project1";
  project2: "project2";
};
export type PlasmicCardExperience__VariantsArgs = {
  project1?: SingleBooleanChoiceArg<"project1">;
  project2?: SingleBooleanChoiceArg<"project2">;
};
type VariantPropType = keyof PlasmicCardExperience__VariantsArgs;
export const PlasmicCardExperience__VariantProps = new Array<VariantPropType>(
  "project1",
  "project2"
);

export type PlasmicCardExperience__ArgsType = {
  number?: string;
  title?: string;
  content?: string;
  project1Content?: string;
  project2Content?: string;
  image11?: React.ComponentProps<typeof PlasmicImg__>["src"];
  image12?: React.ComponentProps<typeof PlasmicImg__>["src"];
};
type ArgPropType = keyof PlasmicCardExperience__ArgsType;
export const PlasmicCardExperience__ArgProps = new Array<ArgPropType>(
  "number",
  "title",
  "content",
  "project1Content",
  "project2Content",
  "image11",
  "image12"
);

export type PlasmicCardExperience__OverridesType = {
  root?: Flex__<"div">;
  number01?: Flex__<"div">;
  number012?: Flex__<"div">;
  titleArtDirection2?: Flex__<"div">;
  relatedWork2?: Flex__<"div">;
  _13?: Flex__<"div">;
  image1?: Flex__<typeof PlasmicImg__>;
  image2?: Flex__<typeof PlasmicImg__>;
  weTakePrideInProvidingOurClientsWithAnUnforgettableExperienceFromStartToFinishFromBrainstormingSessionsToCastingCallsFromScoutingLocationsToPostProductionWeHandleEveryAspectOfTheFilmmakingProcessWithCareAndAttentionToDetailTranslatingEmotionIntoVisualStoriesThatConnectInspireAndEndure?: Flex__<"div">;
  weTakePrideInProvidingOurClientsWithAnUnforgettableExperienceFromStartToFinishFromBrainstormingSessionsToCastingCallsFromScoutingLocationsToPostProductionWeHandleEveryAspectOfTheFilmmakingProcessWithCareAndAttentionToDetailTranslatingEmotionIntoVisualStoriesThatConnectInspireAndEndure2?: Flex__<"div">;
  titleTopNorwegianCapsule?: Flex__<"div">;
  titleTopNorwegianCapsule2?: Flex__<"div">;
  titleTopNorwegianCapsule3?: Flex__<"div">;
  titleTopNorwegianCapsule4?: Flex__<"div">;
};

export interface DefaultCardExperienceProps {
  number?: string;
  title?: string;
  content?: string;
  project1Content?: string;
  project2Content?: string;
  image11?: React.ComponentProps<typeof PlasmicImg__>["src"];
  image12?: React.ComponentProps<typeof PlasmicImg__>["src"];
  project1?: SingleBooleanChoiceArg<"project1">;
  project2?: SingleBooleanChoiceArg<"project2">;
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicCardExperience__RenderFunc(props: {
  variants: PlasmicCardExperience__VariantsArgs;
  args: PlasmicCardExperience__ArgsType;
  overrides: PlasmicCardExperience__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {
          number: "[ 01 ]",
          title: "ART DIRECTION",
          content:
            "Translating emotion into visual stories  that connect, inspire, and endure.",
          project1Content: "Project 1",
          project2Content: "Project 2",
          image11: {
            src: "/plasmic/son_vo/images/yrStH7Lcoh9O5WxFsPetODyteSmPngJpg.jpg",
            fullWidth: 1090,
            fullHeight: 1080,
            aspectRatio: undefined
          },
          image12: {
            src: "/plasmic/son_vo/images/yrStH7Lcoh9O5WxFsPetODyteSmPngJpg.jpg",
            fullWidth: 1090,
            fullHeight: 1080,
            aspectRatio: undefined
          }
        },
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = useCurrentUser?.() || {};

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "project1",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) =>
          (() => {
            try {
              return $state.myHoverState1;
            } catch (e) {
              if (
                e instanceof TypeError ||
                e?.plasmicType === "PlasmicUndefinedDataError"
              ) {
                return undefined;
              }
              throw e;
            }
          })() ?? $props.project1
      },
      {
        path: "myHoverState1",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) =>
          (() => {
            try {
              return false;
            } catch (e) {
              if (
                e instanceof TypeError ||
                e?.plasmicType === "PlasmicUndefinedDataError"
              ) {
                return false;
              }
              throw e;
            }
          })()
      },
      {
        path: "project2",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) =>
          (() => {
            try {
              return $state.myHoverState2;
            } catch (e) {
              if (
                e instanceof TypeError ||
                e?.plasmicType === "PlasmicUndefinedDataError"
              ) {
                return undefined;
              }
              throw e;
            }
          })() ?? $props.project2
      },
      {
        path: "myHoverState2",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) =>
          (() => {
            try {
              return false;
            } catch (e) {
              if (
                e instanceof TypeError ||
                e?.plasmicType === "PlasmicUndefinedDataError"
              ) {
                return false;
              }
              throw e;
            }
          })()
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $q: {},
    $refs
  });

  const styleTokensClassNames = _useStyleTokens();

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        styleTokensClassNames,
        sty.root,
        { [sty.rootproject1]: hasVariant($state, "project1", "project1") }
      )}
    >
      <div
        className={classNames(projectcss.all, sty.freeBox__foXrk, {
          [sty.freeBoxproject1__foXrKuWrEk]: hasVariant(
            $state,
            "project1",
            "project1"
          )
        })}
      >
        <div
          data-plasmic-name={"number01"}
          data-plasmic-override={overrides.number01}
          className={classNames(projectcss.all, sty.number01)}
        >
          <div
            data-plasmic-name={"number012"}
            data-plasmic-override={overrides.number012}
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.number012
            )}
          >
            <React.Fragment>
              {(() => {
                try {
                  return $props.number;
                } catch (e) {
                  if (
                    e instanceof TypeError ||
                    e?.plasmicType === "PlasmicUndefinedDataError"
                  ) {
                    return "[01]";
                  }
                  throw e;
                }
              })()}
            </React.Fragment>
          </div>
        </div>
        <div className={classNames(projectcss.all, sty.freeBox__m1Fy)}>
          <div
            data-plasmic-name={"titleArtDirection2"}
            data-plasmic-override={overrides.titleArtDirection2}
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.titleArtDirection2,
              {
                [sty.titleArtDirection2project1]: hasVariant(
                  $state,
                  "project1",
                  "project1"
                )
              }
            )}
          >
            <React.Fragment>
              {(() => {
                try {
                  return $props.title;
                } catch (e) {
                  if (
                    e instanceof TypeError ||
                    e?.plasmicType === "PlasmicUndefinedDataError"
                  ) {
                    return "ART DIRECTION";
                  }
                  throw e;
                }
              })()}
            </React.Fragment>
          </div>
          <div className={classNames(projectcss.all, sty.freeBox__jfKvs)}>
            <div
              data-plasmic-name={"relatedWork2"}
              data-plasmic-override={overrides.relatedWork2}
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.relatedWork2
              )}
            >
              {"RELATED WORK "}
            </div>
            <div
              data-plasmic-name={"_13"}
              data-plasmic-override={overrides._13}
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty._13
              )}
            >
              {"\u2193 "}
            </div>
          </div>
        </div>
      </div>
      <div
        className={classNames(projectcss.all, sty.freeBox__r0Vw, {
          [sty.freeBoxproject1__r0VwUWrEk]: hasVariant(
            $state,
            "project1",
            "project1"
          )
        })}
      >
        <PlasmicImg__
          data-plasmic-name={"image1"}
          data-plasmic-override={overrides.image1}
          alt={""}
          className={classNames(sty.image1, {
            [sty.image1project1]: hasVariant($state, "project1", "project1"),
            [sty.image1project2]: hasVariant($state, "project2", "project2")
          })}
          displayHeight={"100px"}
          displayMaxHeight={"none"}
          displayMaxWidth={"100%"}
          displayMinHeight={"0"}
          displayMinWidth={"0"}
          displayWidth={"156px"}
          loading={"lazy"}
          src={args.image11}
        />

        <PlasmicImg__
          data-plasmic-name={"image2"}
          data-plasmic-override={overrides.image2}
          alt={""}
          className={classNames(sty.image2, {
            [sty.image2project1]: hasVariant($state, "project1", "project1"),
            [sty.image2project2]: hasVariant($state, "project2", "project2")
          })}
          displayHeight={"100px"}
          displayMaxHeight={"none"}
          displayMaxWidth={"100%"}
          displayMinHeight={"0"}
          displayMinWidth={"0"}
          displayWidth={"156px"}
          loading={"lazy"}
          src={args.image12}
        />

        <div
          className={classNames(projectcss.all, sty.freeBox__cjKsj, {
            [sty.freeBoxproject1__cjKsJuWrEk]: hasVariant(
              $state,
              "project1",
              "project1"
            )
          })}
        >
          <div
            data-plasmic-name={
              "weTakePrideInProvidingOurClientsWithAnUnforgettableExperienceFromStartToFinishFromBrainstormingSessionsToCastingCallsFromScoutingLocationsToPostProductionWeHandleEveryAspectOfTheFilmmakingProcessWithCareAndAttentionToDetailTranslatingEmotionIntoVisualStoriesThatConnectInspireAndEndure"
            }
            data-plasmic-override={
              overrides.weTakePrideInProvidingOurClientsWithAnUnforgettableExperienceFromStartToFinishFromBrainstormingSessionsToCastingCallsFromScoutingLocationsToPostProductionWeHandleEveryAspectOfTheFilmmakingProcessWithCareAndAttentionToDetailTranslatingEmotionIntoVisualStoriesThatConnectInspireAndEndure
            }
            className={classNames(
              projectcss.all,
              sty.weTakePrideInProvidingOurClientsWithAnUnforgettableExperienceFromStartToFinishFromBrainstormingSessionsToCastingCallsFromScoutingLocationsToPostProductionWeHandleEveryAspectOfTheFilmmakingProcessWithCareAndAttentionToDetailTranslatingEmotionIntoVisualStoriesThatConnectInspireAndEndure,
              {
                [sty.weTakePrideInProvidingOurClientsWithAnUnforgettableExperienceFromStartToFinishFromBrainstormingSessionsToCastingCallsFromScoutingLocationsToPostProductionWeHandleEveryAspectOfTheFilmmakingProcessWithCareAndAttentionToDetailTranslatingEmotionIntoVisualStoriesThatConnectInspireAndEndureproject1]:
                  hasVariant($state, "project1", "project1")
              }
            )}
          >
            <div
              data-plasmic-name={
                "weTakePrideInProvidingOurClientsWithAnUnforgettableExperienceFromStartToFinishFromBrainstormingSessionsToCastingCallsFromScoutingLocationsToPostProductionWeHandleEveryAspectOfTheFilmmakingProcessWithCareAndAttentionToDetailTranslatingEmotionIntoVisualStoriesThatConnectInspireAndEndure2"
              }
              data-plasmic-override={
                overrides.weTakePrideInProvidingOurClientsWithAnUnforgettableExperienceFromStartToFinishFromBrainstormingSessionsToCastingCallsFromScoutingLocationsToPostProductionWeHandleEveryAspectOfTheFilmmakingProcessWithCareAndAttentionToDetailTranslatingEmotionIntoVisualStoriesThatConnectInspireAndEndure2
              }
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.weTakePrideInProvidingOurClientsWithAnUnforgettableExperienceFromStartToFinishFromBrainstormingSessionsToCastingCallsFromScoutingLocationsToPostProductionWeHandleEveryAspectOfTheFilmmakingProcessWithCareAndAttentionToDetailTranslatingEmotionIntoVisualStoriesThatConnectInspireAndEndure2,
                {
                  [sty.weTakePrideInProvidingOurClientsWithAnUnforgettableExperienceFromStartToFinishFromBrainstormingSessionsToCastingCallsFromScoutingLocationsToPostProductionWeHandleEveryAspectOfTheFilmmakingProcessWithCareAndAttentionToDetailTranslatingEmotionIntoVisualStoriesThatConnectInspireAndEndure2project1]:
                    hasVariant($state, "project1", "project1")
                }
              )}
            >
              <React.Fragment>
                {(() => {
                  try {
                    return $props.content;
                  } catch (e) {
                    if (
                      e instanceof TypeError ||
                      e?.plasmicType === "PlasmicUndefinedDataError"
                    ) {
                      return "Translating emotion into visual stories \nthat connect, inspire, and endure.";
                    }
                    throw e;
                  }
                })()}
              </React.Fragment>
            </div>
          </div>
          <div
            className={classNames(projectcss.all, sty.freeBox___4Om3J, {
              [sty.freeBoxproject1___4Om3JuWrEk]: hasVariant(
                $state,
                "project1",
                "project1"
              )
            })}
          >
            <HoverController
              className={classNames(
                "__wab_instance",
                sty.hoverController__t3R0P,
                {
                  [sty.hoverControllerproject1__t3R0PuWrEk]: hasVariant(
                    $state,
                    "project1",
                    "project1"
                  )
                }
              )}
              onHoverChange={async isHovered => {
                const $steps = {};

                $steps["updateMyHoverState"] = true
                  ? (() => {
                      const actionArgs = {
                        variable: {
                          objRoot: $state,
                          variablePath: ["myHoverState1"]
                        },
                        operation: 0,
                        value: isHovered
                      };
                      return (({
                        variable,
                        value,
                        startIndex,
                        deleteCount
                      }) => {
                        if (!variable) {
                          return;
                        }
                        const { objRoot, variablePath } = variable;

                        $stateSet(objRoot, variablePath, value);
                        return value;
                      })?.apply(null, [actionArgs]);
                    })()
                  : undefined;
                if (
                  $steps["updateMyHoverState"] != null &&
                  typeof $steps["updateMyHoverState"] === "object" &&
                  typeof $steps["updateMyHoverState"].then === "function"
                ) {
                  $steps["updateMyHoverState"] =
                    await $steps["updateMyHoverState"];
                }
              }}
              trigger={
                <DataCtxReader__>
                  {$ctx => (
                    <div
                      data-plasmic-name={"titleTopNorwegianCapsule"}
                      data-plasmic-override={overrides.titleTopNorwegianCapsule}
                      className={classNames(
                        projectcss.all,
                        sty.titleTopNorwegianCapsule
                      )}
                    >
                      <div
                        data-plasmic-name={"titleTopNorwegianCapsule2"}
                        data-plasmic-override={
                          overrides.titleTopNorwegianCapsule2
                        }
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.titleTopNorwegianCapsule2
                        )}
                      >
                        <React.Fragment>
                          {(() => {
                            try {
                              return $props.project1Content;
                            } catch (e) {
                              if (
                                e instanceof TypeError ||
                                e?.plasmicType === "PlasmicUndefinedDataError"
                              ) {
                                return "NORWEGIAN CAPSULE";
                              }
                              throw e;
                            }
                          })()}
                        </React.Fragment>
                      </div>
                    </div>
                  )}
                </DataCtxReader__>
              }
            />

            <HoverController
              className={classNames(
                "__wab_instance",
                sty.hoverController__dkYqK,
                {
                  [sty.hoverControllerproject1__dkYqKuWrEk]: hasVariant(
                    $state,
                    "project1",
                    "project1"
                  )
                }
              )}
              onHoverChange={async isHovered => {
                const $steps = {};

                $steps["updateMyHoverState"] = true
                  ? (() => {
                      const actionArgs = {
                        variable: {
                          objRoot: $state,
                          variablePath: ["myHoverState2"]
                        },
                        operation: 0,
                        value: isHovered
                      };
                      return (({
                        variable,
                        value,
                        startIndex,
                        deleteCount
                      }) => {
                        if (!variable) {
                          return;
                        }
                        const { objRoot, variablePath } = variable;

                        $stateSet(objRoot, variablePath, value);
                        return value;
                      })?.apply(null, [actionArgs]);
                    })()
                  : undefined;
                if (
                  $steps["updateMyHoverState"] != null &&
                  typeof $steps["updateMyHoverState"] === "object" &&
                  typeof $steps["updateMyHoverState"].then === "function"
                ) {
                  $steps["updateMyHoverState"] =
                    await $steps["updateMyHoverState"];
                }
              }}
              trigger={
                <DataCtxReader__>
                  {$ctx => (
                    <div
                      data-plasmic-name={"titleTopNorwegianCapsule3"}
                      data-plasmic-override={
                        overrides.titleTopNorwegianCapsule3
                      }
                      className={classNames(
                        projectcss.all,
                        sty.titleTopNorwegianCapsule3
                      )}
                    >
                      <div
                        data-plasmic-name={"titleTopNorwegianCapsule4"}
                        data-plasmic-override={
                          overrides.titleTopNorwegianCapsule4
                        }
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.titleTopNorwegianCapsule4,
                          {
                            [sty.titleTopNorwegianCapsule4project1]: hasVariant(
                              $state,
                              "project1",
                              "project1"
                            ),
                            [sty.titleTopNorwegianCapsule4project2]: hasVariant(
                              $state,
                              "project2",
                              "project2"
                            )
                          }
                        )}
                      >
                        <React.Fragment>
                          {(() => {
                            try {
                              return $props.project2Content;
                            } catch (e) {
                              if (
                                e instanceof TypeError ||
                                e?.plasmicType === "PlasmicUndefinedDataError"
                              ) {
                                return "";
                              }
                              throw e;
                            }
                          })()}
                        </React.Fragment>
                      </div>
                    </div>
                  )}
                </DataCtxReader__>
              }
            />
          </div>
        </div>
      </div>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "number01",
    "number012",
    "titleArtDirection2",
    "relatedWork2",
    "_13",
    "image1",
    "image2",
    "weTakePrideInProvidingOurClientsWithAnUnforgettableExperienceFromStartToFinishFromBrainstormingSessionsToCastingCallsFromScoutingLocationsToPostProductionWeHandleEveryAspectOfTheFilmmakingProcessWithCareAndAttentionToDetailTranslatingEmotionIntoVisualStoriesThatConnectInspireAndEndure",
    "weTakePrideInProvidingOurClientsWithAnUnforgettableExperienceFromStartToFinishFromBrainstormingSessionsToCastingCallsFromScoutingLocationsToPostProductionWeHandleEveryAspectOfTheFilmmakingProcessWithCareAndAttentionToDetailTranslatingEmotionIntoVisualStoriesThatConnectInspireAndEndure2",
    "titleTopNorwegianCapsule",
    "titleTopNorwegianCapsule2",
    "titleTopNorwegianCapsule3",
    "titleTopNorwegianCapsule4"
  ],
  number01: ["number01", "number012"],
  number012: ["number012"],
  titleArtDirection2: ["titleArtDirection2"],
  relatedWork2: ["relatedWork2"],
  _13: ["_13"],
  image1: ["image1"],
  image2: ["image2"],
  weTakePrideInProvidingOurClientsWithAnUnforgettableExperienceFromStartToFinishFromBrainstormingSessionsToCastingCallsFromScoutingLocationsToPostProductionWeHandleEveryAspectOfTheFilmmakingProcessWithCareAndAttentionToDetailTranslatingEmotionIntoVisualStoriesThatConnectInspireAndEndure:
    [
      "weTakePrideInProvidingOurClientsWithAnUnforgettableExperienceFromStartToFinishFromBrainstormingSessionsToCastingCallsFromScoutingLocationsToPostProductionWeHandleEveryAspectOfTheFilmmakingProcessWithCareAndAttentionToDetailTranslatingEmotionIntoVisualStoriesThatConnectInspireAndEndure",
      "weTakePrideInProvidingOurClientsWithAnUnforgettableExperienceFromStartToFinishFromBrainstormingSessionsToCastingCallsFromScoutingLocationsToPostProductionWeHandleEveryAspectOfTheFilmmakingProcessWithCareAndAttentionToDetailTranslatingEmotionIntoVisualStoriesThatConnectInspireAndEndure2"
    ],
  weTakePrideInProvidingOurClientsWithAnUnforgettableExperienceFromStartToFinishFromBrainstormingSessionsToCastingCallsFromScoutingLocationsToPostProductionWeHandleEveryAspectOfTheFilmmakingProcessWithCareAndAttentionToDetailTranslatingEmotionIntoVisualStoriesThatConnectInspireAndEndure2:
    [
      "weTakePrideInProvidingOurClientsWithAnUnforgettableExperienceFromStartToFinishFromBrainstormingSessionsToCastingCallsFromScoutingLocationsToPostProductionWeHandleEveryAspectOfTheFilmmakingProcessWithCareAndAttentionToDetailTranslatingEmotionIntoVisualStoriesThatConnectInspireAndEndure2"
    ],
  titleTopNorwegianCapsule: [
    "titleTopNorwegianCapsule",
    "titleTopNorwegianCapsule2"
  ],
  titleTopNorwegianCapsule2: ["titleTopNorwegianCapsule2"],
  titleTopNorwegianCapsule3: [
    "titleTopNorwegianCapsule3",
    "titleTopNorwegianCapsule4"
  ],
  titleTopNorwegianCapsule4: ["titleTopNorwegianCapsule4"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  number01: "div";
  number012: "div";
  titleArtDirection2: "div";
  relatedWork2: "div";
  _13: "div";
  image1: typeof PlasmicImg__;
  image2: typeof PlasmicImg__;
  weTakePrideInProvidingOurClientsWithAnUnforgettableExperienceFromStartToFinishFromBrainstormingSessionsToCastingCallsFromScoutingLocationsToPostProductionWeHandleEveryAspectOfTheFilmmakingProcessWithCareAndAttentionToDetailTranslatingEmotionIntoVisualStoriesThatConnectInspireAndEndure: "div";
  weTakePrideInProvidingOurClientsWithAnUnforgettableExperienceFromStartToFinishFromBrainstormingSessionsToCastingCallsFromScoutingLocationsToPostProductionWeHandleEveryAspectOfTheFilmmakingProcessWithCareAndAttentionToDetailTranslatingEmotionIntoVisualStoriesThatConnectInspireAndEndure2: "div";
  titleTopNorwegianCapsule: "div";
  titleTopNorwegianCapsule2: "div";
  titleTopNorwegianCapsule3: "div";
  titleTopNorwegianCapsule4: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicCardExperience__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicCardExperience__VariantsArgs;
    args?: PlasmicCardExperience__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicCardExperience__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicCardExperience__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicCardExperience__ArgProps,
          internalVariantPropNames: PlasmicCardExperience__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicCardExperience__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicCardExperience";
  } else {
    func.displayName = `PlasmicCardExperience.${nodeName}`;
  }
  return func;
}

export const PlasmicCardExperience = Object.assign(
  // Top-level PlasmicCardExperience renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    number01: makeNodeComponent("number01"),
    number012: makeNodeComponent("number012"),
    titleArtDirection2: makeNodeComponent("titleArtDirection2"),
    relatedWork2: makeNodeComponent("relatedWork2"),
    _13: makeNodeComponent("_13"),
    image1: makeNodeComponent("image1"),
    image2: makeNodeComponent("image2"),
    weTakePrideInProvidingOurClientsWithAnUnforgettableExperienceFromStartToFinishFromBrainstormingSessionsToCastingCallsFromScoutingLocationsToPostProductionWeHandleEveryAspectOfTheFilmmakingProcessWithCareAndAttentionToDetailTranslatingEmotionIntoVisualStoriesThatConnectInspireAndEndure:
      makeNodeComponent(
        "weTakePrideInProvidingOurClientsWithAnUnforgettableExperienceFromStartToFinishFromBrainstormingSessionsToCastingCallsFromScoutingLocationsToPostProductionWeHandleEveryAspectOfTheFilmmakingProcessWithCareAndAttentionToDetailTranslatingEmotionIntoVisualStoriesThatConnectInspireAndEndure"
      ),
    weTakePrideInProvidingOurClientsWithAnUnforgettableExperienceFromStartToFinishFromBrainstormingSessionsToCastingCallsFromScoutingLocationsToPostProductionWeHandleEveryAspectOfTheFilmmakingProcessWithCareAndAttentionToDetailTranslatingEmotionIntoVisualStoriesThatConnectInspireAndEndure2:
      makeNodeComponent(
        "weTakePrideInProvidingOurClientsWithAnUnforgettableExperienceFromStartToFinishFromBrainstormingSessionsToCastingCallsFromScoutingLocationsToPostProductionWeHandleEveryAspectOfTheFilmmakingProcessWithCareAndAttentionToDetailTranslatingEmotionIntoVisualStoriesThatConnectInspireAndEndure2"
      ),
    titleTopNorwegianCapsule: makeNodeComponent("titleTopNorwegianCapsule"),
    titleTopNorwegianCapsule2: makeNodeComponent("titleTopNorwegianCapsule2"),
    titleTopNorwegianCapsule3: makeNodeComponent("titleTopNorwegianCapsule3"),
    titleTopNorwegianCapsule4: makeNodeComponent("titleTopNorwegianCapsule4"),

    // Metadata about props expected for PlasmicCardExperience
    internalVariantProps: PlasmicCardExperience__VariantProps,
    internalArgProps: PlasmicCardExperience__ArgProps
  }
);

export default PlasmicCardExperience;
/* prettier-ignore-end */
