/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

// This code is auto-generated by Plasmic; please do not edit!
// Plasmic Project: bLa1shfC4noziDsvmxjKJF

import { createUseGlobalVariants } from "@plasmicapp/react-web";

import { useScreenVariants as useScreenVariantskczwnCiKgXgw } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: KczwnCiKgXGW/globalVariant

export const _useGlobalVariants = createUseGlobalVariants({
  screen: useScreenVariantskczwnCiKgXgw
});
