/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: bLa1shfC4noziDsvmxjKJF
// Component: u1Kyfwr4MSZG

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { CustomCursorWrapper } from "../../CustomCursorWrapper"; // plasmic-import: GFDn8mn_QNHr/codeComponent
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: bLa1shfC4noziDsvmxjKJF/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: bLa1shfC4noziDsvmxjKJF/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: bLa1shfC4noziDsvmxjKJF/projectcss
import sty from "./PlasmicTemplateCard.module.css"; // plasmic-import: u1Kyfwr4MSZG/css

createPlasmicElementProxy;

export type PlasmicTemplateCard__VariantMembers = {
  hover: "hover";
};
export type PlasmicTemplateCard__VariantsArgs = {
  hover?: SingleBooleanChoiceArg<"hover">;
};
type VariantPropType = keyof PlasmicTemplateCard__VariantsArgs;
export const PlasmicTemplateCard__VariantProps = new Array<VariantPropType>(
  "hover"
);

export type PlasmicTemplateCard__ArgsType = {
  img2?: React.ReactNode;
  container9?: React.ReactNode;
  softwareContainerSoftware2?: React.ReactNode;
};
type ArgPropType = keyof PlasmicTemplateCard__ArgsType;
export const PlasmicTemplateCard__ArgProps = new Array<ArgPropType>(
  "img2",
  "container9",
  "softwareContainerSoftware2"
);

export type PlasmicTemplateCard__OverridesType = {
  linkDesktopColored?: Flex__<"div">;
  customCursorWrapper?: Flex__<typeof CustomCursorWrapper>;
  image?: Flex__<"div">;
  border?: Flex__<"div">;
  screws?: Flex__<"div">;
  _1?: Flex__<"div">;
  _2?: Flex__<"div">;
  _3?: Flex__<"div">;
  _4?: Flex__<"div">;
  overlay2?: Flex__<"div">;
  bottom?: Flex__<"div">;
  top2?: Flex__<"div">;
  templateName?: Flex__<"div">;
  container8?: Flex__<"div">;
  container10?: Flex__<"div">;
};

export interface DefaultTemplateCardProps {
  img2?: React.ReactNode;
  container9?: React.ReactNode;
  softwareContainerSoftware2?: React.ReactNode;
  hover?: SingleBooleanChoiceArg<"hover">;
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicTemplateCard__RenderFunc(props: {
  variants: PlasmicTemplateCard__VariantsArgs;
  args: PlasmicTemplateCard__ArgsType;
  overrides: PlasmicTemplateCard__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = useCurrentUser?.() || {};

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "variable",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => ""
      },
      {
        path: "hover",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => $props.hover
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $q: {},
    $refs
  });

  const styleTokensClassNames = _useStyleTokens();

  return (
    <div
      data-plasmic-name={"linkDesktopColored"}
      data-plasmic-override={overrides.linkDesktopColored}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        styleTokensClassNames,
        sty.linkDesktopColored
      )}
    >
      <CustomCursorWrapper
        data-plasmic-name={"customCursorWrapper"}
        data-plasmic-override={overrides.customCursorWrapper}
        className={classNames("__wab_instance", sty.customCursorWrapper, {
          [sty.customCursorWrapperhover]: hasVariant($state, "hover", "hover")
        })}
        cursorIcon={"/plasmic/son_vo/images/vectorPng3.png"}
      >
        <div
          data-plasmic-name={"image"}
          data-plasmic-override={overrides.image}
          className={classNames(projectcss.all, sty.image)}
        >
          <div
            data-plasmic-name={"border"}
            data-plasmic-override={overrides.border}
            className={classNames(projectcss.all, sty.border)}
          />

          <div
            data-plasmic-name={"screws"}
            data-plasmic-override={overrides.screws}
            className={classNames(projectcss.all, sty.screws)}
          >
            <div
              data-plasmic-name={"_1"}
              data-plasmic-override={overrides._1}
              className={classNames(projectcss.all, sty._1)}
            />

            <div
              data-plasmic-name={"_2"}
              data-plasmic-override={overrides._2}
              className={classNames(projectcss.all, sty._2)}
            />

            <div
              data-plasmic-name={"_3"}
              data-plasmic-override={overrides._3}
              className={classNames(projectcss.all, sty._3)}
            />

            <div
              data-plasmic-name={"_4"}
              data-plasmic-override={overrides._4}
              className={classNames(projectcss.all, sty._4)}
            />
          </div>
          <div
            data-plasmic-name={"overlay2"}
            data-plasmic-override={overrides.overlay2}
            className={classNames(projectcss.all, sty.overlay2, {
              [sty.overlay2hover]: hasVariant($state, "hover", "hover")
            })}
          >
            {renderPlasmicSlot({
              defaultContents: (
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__csb0Z)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"100%"}
                  loading={"lazy"}
                  src={{
                    src: "/plasmic/son_vo/images/frame20Jpg.jpg",
                    fullWidth: 511,
                    fullHeight: 596,
                    aspectRatio: undefined
                  }}
                />
              ),

              value: args.img2
            })}
          </div>
        </div>
      </CustomCursorWrapper>
      <div
        data-plasmic-name={"bottom"}
        data-plasmic-override={overrides.bottom}
        className={classNames(projectcss.all, sty.bottom)}
      >
        <div
          data-plasmic-name={"top2"}
          data-plasmic-override={overrides.top2}
          className={classNames(projectcss.all, sty.top2)}
        >
          <div
            data-plasmic-name={"templateName"}
            data-plasmic-override={overrides.templateName}
            className={classNames(projectcss.all, sty.templateName)}
          >
            <div
              data-plasmic-name={"container8"}
              data-plasmic-override={overrides.container8}
              className={classNames(projectcss.all, sty.container8)}
            >
              {renderPlasmicSlot({
                defaultContents: (
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__dZw7R
                    )}
                  >
                    {"Vectura"}
                  </div>
                ),
                value: args.container9
              })}
            </div>
          </div>
        </div>
        <div
          data-plasmic-name={"container10"}
          data-plasmic-override={overrides.container10}
          className={classNames(projectcss.all, sty.container10)}
        >
          {renderPlasmicSlot({
            defaultContents: (
              <div className={classNames(projectcss.all, sty.freeBox__qrLsn)}>
                <div className={classNames(projectcss.all, sty.freeBox__zl0Sx)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__bEoHv
                    )}
                  >
                    {"Framer"}
                  </div>
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__m0QFu)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__bfvur
                    )}
                  >
                    {"Framer"}
                  </div>
                </div>
                <div
                  className={classNames(projectcss.all, sty.freeBox___3HTu0)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__idsCo
                    )}
                  >
                    {"Framer"}
                  </div>
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__mdfGw)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__xJhCh
                    )}
                  >
                    {"Framer"}
                  </div>
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__yOgF)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__l4V4Y
                    )}
                  >
                    {"Framer"}
                  </div>
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__hnjqN)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__lP0Jn
                    )}
                  >
                    {"Framer"}
                  </div>
                </div>
              </div>
            ),
            value: args.softwareContainerSoftware2
          })}
        </div>
      </div>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  linkDesktopColored: [
    "linkDesktopColored",
    "customCursorWrapper",
    "image",
    "border",
    "screws",
    "_1",
    "_2",
    "_3",
    "_4",
    "overlay2",
    "bottom",
    "top2",
    "templateName",
    "container8",
    "container10"
  ],
  customCursorWrapper: [
    "customCursorWrapper",
    "image",
    "border",
    "screws",
    "_1",
    "_2",
    "_3",
    "_4",
    "overlay2"
  ],
  image: ["image", "border", "screws", "_1", "_2", "_3", "_4", "overlay2"],
  border: ["border"],
  screws: ["screws", "_1", "_2", "_3", "_4"],
  _1: ["_1"],
  _2: ["_2"],
  _3: ["_3"],
  _4: ["_4"],
  overlay2: ["overlay2"],
  bottom: ["bottom", "top2", "templateName", "container8", "container10"],
  top2: ["top2", "templateName", "container8"],
  templateName: ["templateName", "container8"],
  container8: ["container8"],
  container10: ["container10"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  linkDesktopColored: "div";
  customCursorWrapper: typeof CustomCursorWrapper;
  image: "div";
  border: "div";
  screws: "div";
  _1: "div";
  _2: "div";
  _3: "div";
  _4: "div";
  overlay2: "div";
  bottom: "div";
  top2: "div";
  templateName: "div";
  container8: "div";
  container10: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicTemplateCard__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicTemplateCard__VariantsArgs;
    args?: PlasmicTemplateCard__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicTemplateCard__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicTemplateCard__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicTemplateCard__ArgProps,
          internalVariantPropNames: PlasmicTemplateCard__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicTemplateCard__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "linkDesktopColored") {
    func.displayName = "PlasmicTemplateCard";
  } else {
    func.displayName = `PlasmicTemplateCard.${nodeName}`;
  }
  return func;
}

export const PlasmicTemplateCard = Object.assign(
  // Top-level PlasmicTemplateCard renders the root element
  makeNodeComponent("linkDesktopColored"),
  {
    // Helper components rendering sub-elements
    customCursorWrapper: makeNodeComponent("customCursorWrapper"),
    image: makeNodeComponent("image"),
    border: makeNodeComponent("border"),
    screws: makeNodeComponent("screws"),
    _1: makeNodeComponent("_1"),
    _2: makeNodeComponent("_2"),
    _3: makeNodeComponent("_3"),
    _4: makeNodeComponent("_4"),
    overlay2: makeNodeComponent("overlay2"),
    bottom: makeNodeComponent("bottom"),
    top2: makeNodeComponent("top2"),
    templateName: makeNodeComponent("templateName"),
    container8: makeNodeComponent("container8"),
    container10: makeNodeComponent("container10"),

    // Metadata about props expected for PlasmicTemplateCard
    internalVariantProps: PlasmicTemplateCard__VariantProps,
    internalArgProps: PlasmicTemplateCard__ArgProps
  }
);

export default PlasmicTemplateCard;
/* prettier-ignore-end */
