/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: bLa1shfC4noziDsvmxjKJF
// Component: JOkR_GpRIk06

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { HackerText } from "../../HackerText"; // plasmic-import: 3GgRTQcWQU8e/codeComponent
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: bLa1shfC4noziDsvmxjKJF/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: bLa1shfC4noziDsvmxjKJF/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import sty from "./PlasmicNewMenu2.module.css"; // plasmic-import: JOkR_GpRIk06/css

createPlasmicElementProxy;

export type PlasmicNewMenu2__VariantMembers = {
  scrolledState: "scrolledState";
};
export type PlasmicNewMenu2__VariantsArgs = {
  scrolledState?: SingleBooleanChoiceArg<"scrolledState">;
};
type VariantPropType = keyof PlasmicNewMenu2__VariantsArgs;
export const PlasmicNewMenu2__VariantProps = new Array<VariantPropType>(
  "scrolledState"
);

export type PlasmicNewMenu2__ArgsType = { headerTitle?: React.ReactNode };
type ArgPropType = keyof PlasmicNewMenu2__ArgsType;
export const PlasmicNewMenu2__ArgProps = new Array<ArgPropType>("headerTitle");

export type PlasmicNewMenu2__OverridesType = {
  menu?: Flex__<"div">;
  img?: Flex__<typeof PlasmicImg__>;
};

export interface DefaultNewMenu2Props {
  headerTitle?: React.ReactNode;
  scrolledState?: SingleBooleanChoiceArg<"scrolledState">;
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicNewMenu2__RenderFunc(props: {
  variants: PlasmicNewMenu2__VariantsArgs;
  args: PlasmicNewMenu2__ArgsType;
  overrides: PlasmicNewMenu2__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "scrolled",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) =>
          (() => {
            try {
              return $ctx.scrollData.isScrolled;
            } catch (e) {
              if (
                e instanceof TypeError ||
                e?.plasmicType === "PlasmicUndefinedDataError"
              ) {
                return true;
              }
              throw e;
            }
          })()
      },
      {
        path: "scrolledState",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) =>
          $props.scrolledState
      }
    ],

    [$props, $ctx, $refs]
  );

  const currentUser = useCurrentUser?.() || {};

  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $q: {},
    $refs
  });

  const styleTokensClassNames = _useStyleTokens();

  return (
    <div
      data-plasmic-name={"menu"}
      data-plasmic-override={overrides.menu}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        "all",
        "root_reset_bLa1shfC4noziDsvmxjKJF",
        "plasmic_default_styles",
        "plasmic_mixins",
        styleTokensClassNames,
        sty.menu,
        hasVariant($state, "scrolledState", "scrolledState") ? `` : ``,
        {
          [sty.menuscrolledState]: hasVariant(
            $state,
            "scrolledState",
            "scrolledState"
          )
        }
      )}
    >
      <div className={classNames("all", sty.freeBox__qknUp)}>
        <PlasmicImg__
          data-plasmic-name={"img"}
          data-plasmic-override={overrides.img}
          alt={""}
          className={classNames(sty.img)}
          displayHeight={"auto"}
          displayMaxHeight={"none"}
          displayMaxWidth={"100%"}
          displayMinHeight={"0"}
          displayMinWidth={"0"}
          displayWidth={"120px"}
          loading={"lazy"}
          src={{
            src: "/plasmic/son_vo/images/framePng.png",
            fullWidth: 208,
            fullHeight: 96,
            aspectRatio: undefined
          }}
        />
      </div>
      <div className={classNames("all", sty.freeBox___44Q1)}>
        <div className={classNames("all", sty.freeBox__lopyv)}>
          <HackerText
            className={classNames("__wab_instance", sty.hackerText__ybLzV)}
            defaultColor={"#ffffff"}
            hoverColor={"#00ff00"}
            text={"Home"}
          />

          <HackerText
            className={classNames("__wab_instance", sty.hackerText__dsPPq)}
            defaultColor={"#ffffff"}
            hoverColor={"#00ff00"}
            text={"Works"}
          />

          <HackerText
            className={classNames("__wab_instance", sty.hackerText__mAvGv)}
            defaultColor={"#ffffff"}
            hoverColor={"#00ff00"}
            text={"Journey"}
          />

          <HackerText
            className={classNames("__wab_instance", sty.hackerText__giAbD)}
            defaultColor={"#ffffff"}
            hoverColor={"#00ff00"}
            text={"My Services"}
          />
        </div>
      </div>
      <div className={classNames("all", sty.freeBox__x6CJv)}>
        {renderPlasmicSlot({
          defaultContents: "[ 2026 ]",
          value: args.headerTitle,
          className: classNames(sty.slotTargetHeaderTitle)
        })}
      </div>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  menu: ["menu", "img"],
  img: ["img"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  menu: "div";
  img: typeof PlasmicImg__;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicNewMenu2__OverridesType,
  DescendantsType<T>
>;

type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicNewMenu2__VariantsArgs;
    args?: PlasmicNewMenu2__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicNewMenu2__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicNewMenu2__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicNewMenu2__ArgProps,
          internalVariantPropNames: PlasmicNewMenu2__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicNewMenu2__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "menu") {
    func.displayName = "PlasmicNewMenu2";
  } else {
    func.displayName = `PlasmicNewMenu2.${nodeName}`;
  }
  return func;
}

export const PlasmicNewMenu2 = Object.assign(
  // Top-level PlasmicNewMenu2 renders the root element
  makeNodeComponent("menu"),
  {
    // Helper components rendering sub-elements
    img: makeNodeComponent("img"),

    // Metadata about props expected for PlasmicNewMenu2
    internalVariantProps: PlasmicNewMenu2__VariantProps,
    internalArgProps: PlasmicNewMenu2__ArgProps
  }
);

export default PlasmicNewMenu2;
/* prettier-ignore-end */
