/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: bLa1shfC4noziDsvmxjKJF
// Component: pJp_GqmWQ71r

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { _useGlobalVariants } from "./plasmic"; // plasmic-import: bLa1shfC4noziDsvmxjKJF/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: bLa1shfC4noziDsvmxjKJF/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: bLa1shfC4noziDsvmxjKJF/projectcss
import sty from "./PlasmicFotterMain.module.css"; // plasmic-import: pJp_GqmWQ71r/css

import Icon2Icon from "./icons/PlasmicIcon__Icon2"; // plasmic-import: 2WxnB5zdkiqv/icon
import LinkedinSvg2Icon from "./icons/PlasmicIcon__LinkedinSvg2"; // plasmic-import: IGmKTdFrHdSH/icon
import BehanceSvgIcon from "./icons/PlasmicIcon__BehanceSvg"; // plasmic-import: PUdu4Eq0YgkH/icon
import HSvgIcon from "./icons/PlasmicIcon__HSvg"; // plasmic-import: sy98iCjT69--/icon
import SSvgIcon from "./icons/PlasmicIcon__SSvg"; // plasmic-import: NkVFZd6iU3-5/icon
import VSvgIcon from "./icons/PlasmicIcon__VSvg"; // plasmic-import: XBxj4iigjQvC/icon

createPlasmicElementProxy;

export type PlasmicFotterMain__VariantMembers = {};
export type PlasmicFotterMain__VariantsArgs = {};
type VariantPropType = keyof PlasmicFotterMain__VariantsArgs;
export const PlasmicFotterMain__VariantProps = new Array<VariantPropType>();

export type PlasmicFotterMain__ArgsType = {};
type ArgPropType = keyof PlasmicFotterMain__ArgsType;
export const PlasmicFotterMain__ArgProps = new Array<ArgPropType>();

export type PlasmicFotterMain__OverridesType = {
  footer3?: Flex__<"div">;
  container41?: Flex__<"div">;
  frame1618873418?: Flex__<"div">;
  navigation6?: Flex__<"div">;
  link27?: Flex__<"div">;
  frame1618873420?: Flex__<"div">;
  link28?: Flex__<"div">;
  link29?: Flex__<"div">;
  link30?: Flex__<"div">;
  container43?: Flex__<"div">;
  frame1618873422?: Flex__<"div">;
  heading17?: Flex__<"div">;
};

export interface DefaultFotterMainProps {
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicFotterMain__RenderFunc(props: {
  variants: PlasmicFotterMain__VariantsArgs;
  args: PlasmicFotterMain__ArgsType;
  overrides: PlasmicFotterMain__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const globalVariants = _useGlobalVariants();

  const currentUser = useCurrentUser?.() || {};

  const styleTokensClassNames = _useStyleTokens();

  return (
    <div
      data-plasmic-name={"footer3"}
      data-plasmic-override={overrides.footer3}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        styleTokensClassNames,
        sty.footer3
      )}
    >
      <div
        data-plasmic-name={"container41"}
        data-plasmic-override={overrides.container41}
        className={classNames(projectcss.all, sty.container41)}
      >
        <div
          data-plasmic-name={"frame1618873418"}
          data-plasmic-override={overrides.frame1618873418}
          className={classNames(projectcss.all, sty.frame1618873418)}
        >
          <div
            data-plasmic-name={"navigation6"}
            data-plasmic-override={overrides.navigation6}
            className={classNames(projectcss.all, sty.navigation6)}
          >
            <div
              data-plasmic-name={"link27"}
              data-plasmic-override={overrides.link27}
              className={classNames(projectcss.all, sty.link27)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__p0IDw
                )}
              >
                {hasVariant(globalVariants, "screen", "tablet") ? (
                  <React.Fragment>
                    <span
                      className={
                        "plasmic_default__all plasmic_default__span plasmic_default__span__bLa1s"
                      }
                      style={{ fontWeight: 700 }}
                    >
                      {"Interested to work with me?"}
                    </span>
                    <React.Fragment>{"\n"}</React.Fragment>
                    <span
                      className={
                        "plasmic_default__all plasmic_default__span plasmic_default__span__bLa1s"
                      }
                      style={{ fontWeight: 700 }}
                    >
                      {"hongson789987"}
                    </span>
                    <React.Fragment>{"@mail.com"}</React.Fragment>
                  </React.Fragment>
                ) : (
                  <React.Fragment>
                    <span
                      className={
                        "plasmic_default__all plasmic_default__span plasmic_default__span__bLa1s"
                      }
                      style={{ fontWeight: 700 }}
                    >
                      {"Interested to work with me?"}
                    </span>
                    <React.Fragment>{"\n"}</React.Fragment>
                    <span
                      className={
                        "plasmic_default__all plasmic_default__span plasmic_default__span__bLa1s"
                      }
                      style={{ fontWeight: 700 }}
                    >
                      {"hongson789987"}
                    </span>
                    <React.Fragment>{"@mail.com"}</React.Fragment>
                  </React.Fragment>
                )}
              </div>
            </div>
            <div
              data-plasmic-name={"frame1618873420"}
              data-plasmic-override={overrides.frame1618873420}
              className={classNames(projectcss.all, sty.frame1618873420)}
            >
              <div
                data-plasmic-name={"link28"}
                data-plasmic-override={overrides.link28}
                className={classNames(projectcss.all, sty.link28)}
              >
                <Icon2Icon
                  className={classNames(projectcss.all, sty.svg__sfB2O)}
                  role={"img"}
                />

                <PlasmicLink__
                  className={classNames(
                    projectcss.all,
                    projectcss.a,
                    projectcss.a__bLa1s,
                    projectcss.__wab_text,
                    sty.link__wEneb
                  )}
                  component={Link}
                  href={"https://www.facebook.com/vo.hong.son.674759/"}
                  legacyBehavior={false}
                  platform={"nextjs"}
                  target={"_blank"}
                >
                  {"Facebook"}
                </PlasmicLink__>
              </div>
              <div
                data-plasmic-name={"link29"}
                data-plasmic-override={overrides.link29}
                className={classNames(projectcss.all, sty.link29)}
              >
                <div className={classNames(projectcss.all, sty.freeBox__al4Jh)}>
                  <LinkedinSvg2Icon
                    className={classNames(projectcss.all, sty.svg__mjXz)}
                    role={"img"}
                  />
                </div>
                <PlasmicLink__
                  className={classNames(
                    projectcss.all,
                    projectcss.a,
                    projectcss.a__bLa1s,
                    projectcss.__wab_text,
                    sty.link__xYUhD
                  )}
                  component={Link}
                  href={
                    "https://www.linkedin.com/in/s%C6%A1n-v%C3%B5-h%E1%BB%93ng-9a138a240/"
                  }
                  legacyBehavior={false}
                  platform={"nextjs"}
                  target={"_blank"}
                >
                  {"LinkedIn"}
                </PlasmicLink__>
              </div>
              <div
                data-plasmic-name={"link30"}
                data-plasmic-override={overrides.link30}
                className={classNames(projectcss.all, sty.link30)}
              >
                <div className={classNames(projectcss.all, sty.freeBox__n3Oul)}>
                  <BehanceSvgIcon
                    className={classNames(projectcss.all, sty.svg__oJr32)}
                    role={"img"}
                  />
                </div>
                <PlasmicLink__
                  className={classNames(
                    projectcss.all,
                    projectcss.a,
                    projectcss.a__bLa1s,
                    projectcss.__wab_text,
                    sty.link__eC7U4
                  )}
                  component={Link}
                  href={"https://www.behance.net/vhngsn"}
                  legacyBehavior={false}
                  platform={"nextjs"}
                  target={"_blank"}
                >
                  {"Behance"}
                </PlasmicLink__>
              </div>
            </div>
            <div
              data-plasmic-name={"container43"}
              data-plasmic-override={overrides.container43}
              className={classNames(projectcss.all, sty.container43)}
            >
              <div
                data-plasmic-name={"frame1618873422"}
                data-plasmic-override={overrides.frame1618873422}
                className={classNames(projectcss.all, sty.frame1618873422)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__pqy7Y
                  )}
                >
                  {"(+84) 35 765 2075"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__lYxxo
                  )}
                >
                  {"hongson789987@gmail.com"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__wqQZp
                  )}
                >
                  {"Contact with me"}
                </div>
              </div>
            </div>
          </div>
        </div>
        <div
          data-plasmic-name={"heading17"}
          data-plasmic-override={overrides.heading17}
          className={classNames(projectcss.all, sty.heading17)}
        >
          <HSvgIcon
            className={classNames(projectcss.all, sty.svg__zOngi)}
            role={"img"}
          />

          <SSvgIcon
            className={classNames(projectcss.all, sty.svg__lzbwl)}
            role={"img"}
          />

          <VSvgIcon
            className={classNames(projectcss.all, sty.svg___1ZzsS)}
            role={"img"}
          />
        </div>
      </div>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  footer3: [
    "footer3",
    "container41",
    "frame1618873418",
    "navigation6",
    "link27",
    "frame1618873420",
    "link28",
    "link29",
    "link30",
    "container43",
    "frame1618873422",
    "heading17"
  ],
  container41: [
    "container41",
    "frame1618873418",
    "navigation6",
    "link27",
    "frame1618873420",
    "link28",
    "link29",
    "link30",
    "container43",
    "frame1618873422",
    "heading17"
  ],
  frame1618873418: [
    "frame1618873418",
    "navigation6",
    "link27",
    "frame1618873420",
    "link28",
    "link29",
    "link30",
    "container43",
    "frame1618873422"
  ],
  navigation6: [
    "navigation6",
    "link27",
    "frame1618873420",
    "link28",
    "link29",
    "link30",
    "container43",
    "frame1618873422"
  ],
  link27: ["link27"],
  frame1618873420: ["frame1618873420", "link28", "link29", "link30"],
  link28: ["link28"],
  link29: ["link29"],
  link30: ["link30"],
  container43: ["container43", "frame1618873422"],
  frame1618873422: ["frame1618873422"],
  heading17: ["heading17"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  footer3: "div";
  container41: "div";
  frame1618873418: "div";
  navigation6: "div";
  link27: "div";
  frame1618873420: "div";
  link28: "div";
  link29: "div";
  link30: "div";
  container43: "div";
  frame1618873422: "div";
  heading17: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicFotterMain__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicFotterMain__VariantsArgs;
    args?: PlasmicFotterMain__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicFotterMain__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicFotterMain__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicFotterMain__ArgProps,
          internalVariantPropNames: PlasmicFotterMain__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicFotterMain__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "footer3") {
    func.displayName = "PlasmicFotterMain";
  } else {
    func.displayName = `PlasmicFotterMain.${nodeName}`;
  }
  return func;
}

export const PlasmicFotterMain = Object.assign(
  // Top-level PlasmicFotterMain renders the root element
  makeNodeComponent("footer3"),
  {
    // Helper components rendering sub-elements
    container41: makeNodeComponent("container41"),
    frame1618873418: makeNodeComponent("frame1618873418"),
    navigation6: makeNodeComponent("navigation6"),
    link27: makeNodeComponent("link27"),
    frame1618873420: makeNodeComponent("frame1618873420"),
    link28: makeNodeComponent("link28"),
    link29: makeNodeComponent("link29"),
    link30: makeNodeComponent("link30"),
    container43: makeNodeComponent("container43"),
    frame1618873422: makeNodeComponent("frame1618873422"),
    heading17: makeNodeComponent("heading17"),

    // Metadata about props expected for PlasmicFotterMain
    internalVariantProps: PlasmicFotterMain__VariantProps,
    internalArgProps: PlasmicFotterMain__ArgProps
  }
);

export default PlasmicFotterMain;
/* prettier-ignore-end */
