/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: bLa1shfC4noziDsvmxjKJF
// Component: SsxhGEazCsmL

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { HoverController } from "../../HoverController"; // plasmic-import: NVKDfXP9Roz4/codeComponent
import { Video } from "@plasmicpkgs/plasmic-basic-components";
import { Fetcher } from "@plasmicapp/react-web/lib/data-sources";
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: bLa1shfC4noziDsvmxjKJF/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: bLa1shfC4noziDsvmxjKJF/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import sty from "./PlasmicTest2.module.css"; // plasmic-import: SsxhGEazCsmL/css

createPlasmicElementProxy;

export type PlasmicTest2__VariantMembers = {
  project1: "project1";
};
export type PlasmicTest2__VariantsArgs = {
  project1?: SingleBooleanChoiceArg<"project1">;
};
type VariantPropType = keyof PlasmicTest2__VariantsArgs;
export const PlasmicTest2__VariantProps = new Array<VariantPropType>(
  "project1"
);

export type PlasmicTest2__ArgsType = {
  video?: string;
  videoCondition?: boolean;
  imageCondition?: boolean;
  link?: string;
  title?: string;
  image2?: string;
  tag1?: boolean;
  tag22?: boolean;
  tag32?: boolean;
  tag42?: boolean;
  tag52?: boolean;
};
type ArgPropType = keyof PlasmicTest2__ArgsType;
export const PlasmicTest2__ArgProps = new Array<ArgPropType>(
  "video",
  "videoCondition",
  "imageCondition",
  "link",
  "title",
  "image2",
  "tag1",
  "tag22",
  "tag32",
  "tag42",
  "tag52"
);

export type PlasmicTest2__OverridesType = {
  linkDesktopColored?: Flex__<"div">;
  image?: Flex__<"div">;
  border?: Flex__<"div">;
  screws?: Flex__<"div">;
  _1?: Flex__<"div">;
  _2?: Flex__<"div">;
  _3?: Flex__<"div">;
  _4?: Flex__<"div">;
  overlay2?: Flex__<"div">;
  link?: Flex__<"a"> & Partial<LinkProps>;
  hoverController?: Flex__<typeof HoverController>;
  htmlVideo?: Flex__<typeof Video>;
  bottom?: Flex__<"div">;
  top2?: Flex__<"div">;
  templateName?: Flex__<"div">;
  container10?: Flex__<"div">;
  tag12?: Flex__<"div">;
  tag2?: Flex__<"div">;
  tag3?: Flex__<"div">;
  tag4?: Flex__<"div">;
  tag5?: Flex__<"div">;
};

export interface DefaultTest2Props {
  video?: string;
  videoCondition?: boolean;
  imageCondition?: boolean;
  link?: string;
  title?: string;
  image2?: string;
  tag1?: boolean;
  tag22?: boolean;
  tag32?: boolean;
  tag42?: boolean;
  tag52?: boolean;
  project1?: SingleBooleanChoiceArg<"project1">;
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicTest2__RenderFunc(props: {
  variants: PlasmicTest2__VariantsArgs;
  args: PlasmicTest2__ArgsType;
  overrides: PlasmicTest2__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {
          video:
            "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.webm",
          videoCondition: false,
          imageCondition: true,
          image2:
            "https://framerusercontent.com/images/kPjJi3SaQayZ8Z3vprpR1gKZ47U.webp",
          tag1: true,
          tag22: true,
          tag32: true,
          tag42: true,
          tag52: true
        },
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "project1",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) =>
          (() => {
            try {
              return $state.myHoverState1;
            } catch (e) {
              if (
                e instanceof TypeError ||
                e?.plasmicType === "PlasmicUndefinedDataError"
              ) {
                return undefined;
              }
              throw e;
            }
          })() ?? $props.project1
      },
      {
        path: "myHoverState1",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) =>
          (() => {
            try {
              return false;
            } catch (e) {
              if (
                e instanceof TypeError ||
                e?.plasmicType === "PlasmicUndefinedDataError"
              ) {
                return false;
              }
              throw e;
            }
          })()
      }
    ],

    [$props, $ctx, $refs]
  );

  const currentUser = useCurrentUser?.() || {};

  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $q: {},
    $refs
  });

  const styleTokensClassNames = _useStyleTokens();

  return (
    <div
      data-plasmic-name={"linkDesktopColored"}
      data-plasmic-override={overrides.linkDesktopColored}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        "all",
        "root_reset_bLa1shfC4noziDsvmxjKJF",
        "plasmic_default_styles",
        "plasmic_mixins",
        styleTokensClassNames,
        sty.linkDesktopColored,
        {
          [sty.linkDesktopColoredproject1]: hasVariant(
            $state,
            "project1",
            "project1"
          )
        }
      )}
    >
      <div
        data-plasmic-name={"image"}
        data-plasmic-override={overrides.image}
        className={classNames("all", sty.image)}
      >
        <div
          data-plasmic-name={"border"}
          data-plasmic-override={overrides.border}
          className={classNames("all", sty.border)}
        />

        <div
          data-plasmic-name={"screws"}
          data-plasmic-override={overrides.screws}
          className={classNames("all", sty.screws, {
            [sty.screwsproject1]: hasVariant($state, "project1", "project1")
          })}
        >
          <div
            data-plasmic-name={"_1"}
            data-plasmic-override={overrides._1}
            className={classNames("all", sty._1)}
          />

          <div
            data-plasmic-name={"_2"}
            data-plasmic-override={overrides._2}
            className={classNames("all", sty._2)}
          />

          <div
            data-plasmic-name={"_3"}
            data-plasmic-override={overrides._3}
            className={classNames("all", sty._3)}
          />

          <div
            data-plasmic-name={"_4"}
            data-plasmic-override={overrides._4}
            className={classNames("all", sty._4)}
          />
        </div>
        <div
          data-plasmic-name={"overlay2"}
          data-plasmic-override={overrides.overlay2}
          className={classNames("all", sty.overlay2, {
            [sty.overlay2project1]: hasVariant($state, "project1", "project1")
          })}
        >
          <PlasmicLink__
            data-plasmic-name={"link"}
            data-plasmic-override={overrides.link}
            className={classNames("all", "a", "a__bLa1s", sty.link, {
              [sty.linkproject1]: hasVariant($state, "project1", "project1")
            })}
            component={Link}
            href={args.link}
            legacyBehavior={false}
            platform={"nextjs"}
          >
            <HoverController
              data-plasmic-name={"hoverController"}
              data-plasmic-override={overrides.hoverController}
              className={classNames("__wab_instance", sty.hoverController, {
                [sty.hoverControllerproject1]: hasVariant(
                  $state,
                  "project1",
                  "project1"
                )
              })}
              onHoverChange={async isHovered => {
                const $steps = {};

                $steps["updateMyHoverState"] = true
                  ? (() => {
                      const actionArgs = {
                        variable: {
                          objRoot: $state,
                          variablePath: ["myHoverState1"]
                        },
                        operation: 0,
                        value: isHovered
                      };
                      return (({
                        variable,
                        value,
                        startIndex,
                        deleteCount
                      }) => {
                        if (!variable) {
                          return;
                        }
                        const { objRoot, variablePath } = variable;

                        $stateSet(objRoot, variablePath, value);
                        return value;
                      })?.apply(null, [actionArgs]);
                    })()
                  : undefined;
                if (
                  $steps["updateMyHoverState"] != null &&
                  typeof $steps["updateMyHoverState"] === "object" &&
                  typeof $steps["updateMyHoverState"].then === "function"
                ) {
                  $steps["updateMyHoverState"] =
                    await $steps["updateMyHoverState"];
                }
              }}
              trigger={
                <DataCtxReader__>
                  {$ctx => (
                    <div className={classNames("all", sty.freeBox___2AAjN)}>
                      {(() => {
                        try {
                          return $props.videoCondition;
                        } catch (e) {
                          if (
                            e instanceof TypeError ||
                            e?.plasmicType === "PlasmicUndefinedDataError"
                          ) {
                            return true;
                          }
                          throw e;
                        }
                      })() ? (
                        <Video
                          data-plasmic-name={"htmlVideo"}
                          data-plasmic-override={overrides.htmlVideo}
                          autoPlay={true}
                          className={classNames(
                            "__wab_instance",
                            sty.htmlVideo,
                            {
                              [sty.htmlVideoproject1]: hasVariant(
                                $state,
                                "project1",
                                "project1"
                              )
                            }
                          )}
                          controls={false}
                          loop={true}
                          muted={true}
                          ref={ref => {
                            $refs["htmlVideo"] = ref;
                          }}
                          src={args.video}
                        />
                      ) : null}
                      {(() => {
                        try {
                          return $props.imageCondition;
                        } catch (e) {
                          if (
                            e instanceof TypeError ||
                            e?.plasmicType === "PlasmicUndefinedDataError"
                          ) {
                            return true;
                          }
                          throw e;
                        }
                      })() ? (
                        <PlasmicImg__
                          alt={""}
                          className={classNames(sty.img__k3ZoB, {
                            [sty.imgproject1__k3ZoBqzAbD]: hasVariant(
                              $state,
                              "project1",
                              "project1"
                            )
                          })}
                          displayHeight={"100%"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"100%"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"100%"}
                          loading={"lazy"}
                          src={(() => {
                            try {
                              return $props.image2;
                            } catch (e) {
                              if (
                                e instanceof TypeError ||
                                e?.plasmicType === "PlasmicUndefinedDataError"
                              ) {
                                return undefined;
                              }
                              throw e;
                            }
                          })()}
                        />
                      ) : null}
                      <PlasmicImg__
                        alt={""}
                        className={classNames(sty.img__ejkXq, {
                          [sty.imgproject1__ejkXqQzAbD]: hasVariant(
                            $state,
                            "project1",
                            "project1"
                          )
                        })}
                        displayHeight={
                          hasVariant($state, "project1", "project1")
                            ? "auto"
                            : "auto"
                        }
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={
                          hasVariant($state, "project1", "project1")
                            ? "100%"
                            : "100%"
                        }
                        loading={"lazy"}
                        src={(() => {
                          try {
                            return $props.image2;
                          } catch (e) {
                            if (
                              e instanceof TypeError ||
                              e?.plasmicType === "PlasmicUndefinedDataError"
                            ) {
                              return undefined;
                            }
                            throw e;
                          }
                        })()}
                      />
                    </div>
                  )}
                </DataCtxReader__>
              }
            />
          </PlasmicLink__>
        </div>
        <div
          className={classNames("all", sty.freeBox___6JVl6, {
            [sty.freeBoxproject1___6JVl6QzAbD]: hasVariant(
              $state,
              "project1",
              "project1"
            )
          })}
        />
      </div>
      <div
        data-plasmic-name={"bottom"}
        data-plasmic-override={overrides.bottom}
        className={classNames("all", sty.bottom, {
          [sty.bottomproject1]: hasVariant($state, "project1", "project1")
        })}
      >
        <div
          data-plasmic-name={"top2"}
          data-plasmic-override={overrides.top2}
          className={classNames("all", sty.top2)}
        >
          <div
            data-plasmic-name={"templateName"}
            data-plasmic-override={overrides.templateName}
            className={classNames("all", sty.templateName, {
              [sty.templateNameproject1]: hasVariant(
                $state,
                "project1",
                "project1"
              )
            })}
          >
            <div
              className={classNames("all", "__wab_text", sty.text___7Blqc, {
                [sty.textproject1___7BlqcQzAbD]: hasVariant(
                  $state,
                  "project1",
                  "project1"
                )
              })}
            >
              <React.Fragment>
                {(() => {
                  try {
                    return $props.title;
                  } catch (e) {
                    if (
                      e instanceof TypeError ||
                      e?.plasmicType === "PlasmicUndefinedDataError"
                    ) {
                      return "Vectura";
                    }
                    throw e;
                  }
                })()}
              </React.Fragment>
            </div>
          </div>
        </div>
        <div
          data-plasmic-name={"container10"}
          data-plasmic-override={overrides.container10}
          className={classNames("all", sty.container10, {
            [sty.container10project1]: hasVariant(
              $state,
              "project1",
              "project1"
            )
          })}
        >
          <div className={classNames("all", sty.freeBox__a0UDa)}>
            {(() => {
              try {
                return $props.tag1;
              } catch (e) {
                if (
                  e instanceof TypeError ||
                  e?.plasmicType === "PlasmicUndefinedDataError"
                ) {
                  return true;
                }
                throw e;
              }
            })() ? (
              <div
                data-plasmic-name={"tag12"}
                data-plasmic-override={overrides.tag12}
                className={classNames("all", sty.tag12)}
              >
                <div
                  className={classNames("all", "__wab_text", sty.text__j6Qeu)}
                >
                  {"UI"}
                </div>
              </div>
            ) : null}
            {(() => {
              try {
                return $props.tag22;
              } catch (e) {
                if (
                  e instanceof TypeError ||
                  e?.plasmicType === "PlasmicUndefinedDataError"
                ) {
                  return true;
                }
                throw e;
              }
            })() ? (
              <div
                data-plasmic-name={"tag2"}
                data-plasmic-override={overrides.tag2}
                className={classNames("all", sty.tag2)}
              >
                <div
                  className={classNames("all", "__wab_text", sty.text__atmGt)}
                >
                  {"UX"}
                </div>
              </div>
            ) : null}
            {(() => {
              try {
                return $props.tag32;
              } catch (e) {
                if (
                  e instanceof TypeError ||
                  e?.plasmicType === "PlasmicUndefinedDataError"
                ) {
                  return true;
                }
                throw e;
              }
            })() ? (
              <div
                data-plasmic-name={"tag3"}
                data-plasmic-override={overrides.tag3}
                className={classNames("all", sty.tag3)}
              >
                <div
                  className={classNames("all", "__wab_text", sty.text__fncgH)}
                >
                  {"Framer"}
                </div>
              </div>
            ) : null}
            {(() => {
              try {
                return $props.tag42;
              } catch (e) {
                if (
                  e instanceof TypeError ||
                  e?.plasmicType === "PlasmicUndefinedDataError"
                ) {
                  return true;
                }
                throw e;
              }
            })() ? (
              <div
                data-plasmic-name={"tag4"}
                data-plasmic-override={overrides.tag4}
                className={classNames("all", sty.tag4)}
              >
                <div
                  className={classNames("all", "__wab_text", sty.text__mF8G7)}
                >
                  {"E-COMMERCE"}
                </div>
              </div>
            ) : null}
            {(() => {
              try {
                return $props.tag52;
              } catch (e) {
                if (
                  e instanceof TypeError ||
                  e?.plasmicType === "PlasmicUndefinedDataError"
                ) {
                  return true;
                }
                throw e;
              }
            })() ? (
              <div
                data-plasmic-name={"tag5"}
                data-plasmic-override={overrides.tag5}
                className={classNames("all", sty.tag5)}
              >
                <div
                  className={classNames("all", "__wab_text", sty.text__lR61X)}
                >
                  {"BRAND IDENTITY"}
                </div>
              </div>
            ) : null}
          </div>
        </div>
      </div>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  linkDesktopColored: [
    "linkDesktopColored",
    "image",
    "border",
    "screws",
    "_1",
    "_2",
    "_3",
    "_4",
    "overlay2",
    "link",
    "hoverController",
    "htmlVideo",
    "bottom",
    "top2",
    "templateName",
    "container10",
    "tag12",
    "tag2",
    "tag3",
    "tag4",
    "tag5"
  ],

  image: [
    "image",
    "border",
    "screws",
    "_1",
    "_2",
    "_3",
    "_4",
    "overlay2",
    "link",
    "hoverController",
    "htmlVideo"
  ],

  border: ["border"],
  screws: ["screws", "_1", "_2", "_3", "_4"],
  _1: ["_1"],
  _2: ["_2"],
  _3: ["_3"],
  _4: ["_4"],
  overlay2: ["overlay2", "link", "hoverController", "htmlVideo"],
  link: ["link", "hoverController", "htmlVideo"],
  hoverController: ["hoverController", "htmlVideo"],
  htmlVideo: ["htmlVideo"],
  bottom: [
    "bottom",
    "top2",
    "templateName",
    "container10",
    "tag12",
    "tag2",
    "tag3",
    "tag4",
    "tag5"
  ],

  top2: ["top2", "templateName"],
  templateName: ["templateName"],
  container10: ["container10", "tag12", "tag2", "tag3", "tag4", "tag5"],
  tag12: ["tag12"],
  tag2: ["tag2"],
  tag3: ["tag3"],
  tag4: ["tag4"],
  tag5: ["tag5"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  linkDesktopColored: "div";
  image: "div";
  border: "div";
  screws: "div";
  _1: "div";
  _2: "div";
  _3: "div";
  _4: "div";
  overlay2: "div";
  link: "a";
  hoverController: typeof HoverController;
  htmlVideo: typeof Video;
  bottom: "div";
  top2: "div";
  templateName: "div";
  container10: "div";
  tag12: "div";
  tag2: "div";
  tag3: "div";
  tag4: "div";
  tag5: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicTest2__OverridesType,
  DescendantsType<T>
>;

type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicTest2__VariantsArgs;
    args?: PlasmicTest2__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicTest2__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicTest2__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicTest2__ArgProps,
          internalVariantPropNames: PlasmicTest2__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicTest2__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "linkDesktopColored") {
    func.displayName = "PlasmicTest2";
  } else {
    func.displayName = `PlasmicTest2.${nodeName}`;
  }
  return func;
}

export const PlasmicTest2 = Object.assign(
  // Top-level PlasmicTest2 renders the root element
  makeNodeComponent("linkDesktopColored"),
  {
    // Helper components rendering sub-elements
    image: makeNodeComponent("image"),
    border: makeNodeComponent("border"),
    screws: makeNodeComponent("screws"),
    _1: makeNodeComponent("_1"),
    _2: makeNodeComponent("_2"),
    _3: makeNodeComponent("_3"),
    _4: makeNodeComponent("_4"),
    overlay2: makeNodeComponent("overlay2"),
    link: makeNodeComponent("link"),
    hoverController: makeNodeComponent("hoverController"),
    htmlVideo: makeNodeComponent("htmlVideo"),
    bottom: makeNodeComponent("bottom"),
    top2: makeNodeComponent("top2"),
    templateName: makeNodeComponent("templateName"),
    container10: makeNodeComponent("container10"),
    tag12: makeNodeComponent("tag12"),
    tag2: makeNodeComponent("tag2"),
    tag3: makeNodeComponent("tag3"),
    tag4: makeNodeComponent("tag4"),
    tag5: makeNodeComponent("tag5"),

    // Metadata about props expected for PlasmicTest2
    internalVariantProps: PlasmicTest2__VariantProps,
    internalArgProps: PlasmicTest2__ArgProps
  }
);

export default PlasmicTest2;
/* prettier-ignore-end */
