/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: bLa1shfC4noziDsvmxjKJF
// Component: sVhN06_u5KJ1

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { _useGlobalVariants } from "./plasmic"; // plasmic-import: bLa1shfC4noziDsvmxjKJF/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: bLa1shfC4noziDsvmxjKJF/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import sty from "./PlasmicTickerHeader.module.css"; // plasmic-import: sVhN06_u5KJ1/css

createPlasmicElementProxy;

export type PlasmicTickerHeader__VariantMembers = {};
export type PlasmicTickerHeader__VariantsArgs = {};
type VariantPropType = keyof PlasmicTickerHeader__VariantsArgs;
export const PlasmicTickerHeader__VariantProps = new Array<VariantPropType>();

export type PlasmicTickerHeader__ArgsType = {};
type ArgPropType = keyof PlasmicTickerHeader__ArgsType;
export const PlasmicTickerHeader__ArgProps = new Array<ArgPropType>();

export type PlasmicTickerHeader__OverridesType = {
  tickerHeader?: Flex__<"div">;
  container?: Flex__<"div">;
  container2?: Flex__<"div">;
  text?: Flex__<"div">;
  text2?: Flex__<"div">;
  container3?: Flex__<"div">;
  text3?: Flex__<"div">;
  text4?: Flex__<"div">;
  container4?: Flex__<"div">;
  text5?: Flex__<"div">;
  text6?: Flex__<"div">;
  container5?: Flex__<"div">;
  text7?: Flex__<"div">;
  text8?: Flex__<"div">;
  container6?: Flex__<"div">;
  container7?: Flex__<"div">;
  text9?: Flex__<"div">;
  text10?: Flex__<"div">;
  container8?: Flex__<"div">;
  text11?: Flex__<"div">;
  text12?: Flex__<"div">;
  container9?: Flex__<"div">;
  text13?: Flex__<"div">;
  text14?: Flex__<"div">;
  container10?: Flex__<"div">;
  text15?: Flex__<"div">;
  text16?: Flex__<"div">;
};

export interface DefaultTickerHeaderProps {
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicTickerHeader__RenderFunc(props: {
  variants: PlasmicTickerHeader__VariantsArgs;
  args: PlasmicTickerHeader__ArgsType;
  overrides: PlasmicTickerHeader__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = useCurrentUser?.() || {};

  const styleTokensClassNames = _useStyleTokens();

  return (
    <div
      data-plasmic-name={"tickerHeader"}
      data-plasmic-override={overrides.tickerHeader}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        "all",
        "root_reset_bLa1shfC4noziDsvmxjKJF",
        "plasmic_default_styles",
        "plasmic_mixins",
        styleTokensClassNames,
        sty.tickerHeader
      )}
    >
      <div
        data-plasmic-name={"container"}
        data-plasmic-override={overrides.container}
        className={classNames("all", sty.container)}
      >
        <div
          data-plasmic-name={"container2"}
          data-plasmic-override={overrides.container2}
          className={classNames("all", sty.container2)}
        >
          <div
            data-plasmic-name={"text"}
            data-plasmic-override={overrides.text}
            className={classNames("all", sty.text)}
          >
            <div className={classNames("all", "__wab_text", sty.text__tReW)}>
              {"BUILT WITH LOVE FOR THE WEBFLOW COMMUNITY"}
            </div>
          </div>
          <div
            data-plasmic-name={"text2"}
            data-plasmic-override={overrides.text2}
            className={classNames("all", sty.text2)}
          >
            <div className={classNames("all", "__wab_text", sty.text__sNeF)}>
              {"|"}
            </div>
          </div>
        </div>
        <div
          data-plasmic-name={"container3"}
          data-plasmic-override={overrides.container3}
          className={classNames("all", sty.container3)}
        >
          <div
            data-plasmic-name={"text3"}
            data-plasmic-override={overrides.text3}
            className={classNames("all", sty.text3)}
          >
            <div className={classNames("all", "__wab_text", sty.text__stnDy)}>
              {"BUILT WITH LOVE FOR THE WEBFLOW COMMUNITY"}
            </div>
          </div>
          <div
            data-plasmic-name={"text4"}
            data-plasmic-override={overrides.text4}
            className={classNames("all", sty.text4)}
          >
            <div className={classNames("all", "__wab_text", sty.text__hIoF)}>
              {"|"}
            </div>
          </div>
        </div>
        <div
          data-plasmic-name={"container4"}
          data-plasmic-override={overrides.container4}
          className={classNames("all", sty.container4)}
        >
          <div
            data-plasmic-name={"text5"}
            data-plasmic-override={overrides.text5}
            className={classNames("all", sty.text5)}
          >
            <div className={classNames("all", "__wab_text", sty.text__nHnAq)}>
              {"BUILT WITH LOVE FOR THE WEBFLOW COMMUNITY"}
            </div>
          </div>
          <div
            data-plasmic-name={"text6"}
            data-plasmic-override={overrides.text6}
            className={classNames("all", sty.text6)}
          >
            <div className={classNames("all", "__wab_text", sty.text__rYjf6)}>
              {"|"}
            </div>
          </div>
        </div>
        <div
          data-plasmic-name={"container5"}
          data-plasmic-override={overrides.container5}
          className={classNames("all", sty.container5)}
        >
          <div
            data-plasmic-name={"text7"}
            data-plasmic-override={overrides.text7}
            className={classNames("all", sty.text7)}
          >
            <div className={classNames("all", "__wab_text", sty.text__r1Eed)}>
              {"BUILT WITH LOVE FOR THE WEBFLOW COMMUNITY"}
            </div>
          </div>
          <div
            data-plasmic-name={"text8"}
            data-plasmic-override={overrides.text8}
            className={classNames("all", sty.text8)}
          >
            <div className={classNames("all", "__wab_text", sty.text__tfqPz)}>
              {"|"}
            </div>
          </div>
        </div>
      </div>
      <div
        data-plasmic-name={"container6"}
        data-plasmic-override={overrides.container6}
        className={classNames("all", sty.container6)}
      >
        <div
          data-plasmic-name={"container7"}
          data-plasmic-override={overrides.container7}
          className={classNames("all", sty.container7)}
        >
          <div
            data-plasmic-name={"text9"}
            data-plasmic-override={overrides.text9}
            className={classNames("all", sty.text9)}
          >
            <div className={classNames("all", "__wab_text", sty.text__ibBw2)}>
              {"BUILT WITH LOVE FOR THE WEBFLOW COMMUNITY"}
            </div>
          </div>
          <div
            data-plasmic-name={"text10"}
            data-plasmic-override={overrides.text10}
            className={classNames("all", sty.text10)}
          >
            <div className={classNames("all", "__wab_text", sty.text__eDh8A)}>
              {"|"}
            </div>
          </div>
        </div>
        <div
          data-plasmic-name={"container8"}
          data-plasmic-override={overrides.container8}
          className={classNames("all", sty.container8)}
        >
          <div
            data-plasmic-name={"text11"}
            data-plasmic-override={overrides.text11}
            className={classNames("all", sty.text11)}
          >
            <div className={classNames("all", "__wab_text", sty.text___4OrOi)}>
              {"BUILT WITH LOVE FOR THE WEBFLOW COMMUNITY"}
            </div>
          </div>
          <div
            data-plasmic-name={"text12"}
            data-plasmic-override={overrides.text12}
            className={classNames("all", sty.text12)}
          >
            <div className={classNames("all", "__wab_text", sty.text__dFyqn)}>
              {"|"}
            </div>
          </div>
        </div>
        <div
          data-plasmic-name={"container9"}
          data-plasmic-override={overrides.container9}
          className={classNames("all", sty.container9)}
        >
          <div
            data-plasmic-name={"text13"}
            data-plasmic-override={overrides.text13}
            className={classNames("all", sty.text13)}
          >
            <div className={classNames("all", "__wab_text", sty.text__k2Bkw)}>
              {"BUILT WITH LOVE FOR THE WEBFLOW COMMUNITY"}
            </div>
          </div>
          <div
            data-plasmic-name={"text14"}
            data-plasmic-override={overrides.text14}
            className={classNames("all", sty.text14)}
          >
            <div className={classNames("all", "__wab_text", sty.text__gH)}>
              {"|"}
            </div>
          </div>
        </div>
        <div
          data-plasmic-name={"container10"}
          data-plasmic-override={overrides.container10}
          className={classNames("all", sty.container10)}
        >
          <div
            data-plasmic-name={"text15"}
            data-plasmic-override={overrides.text15}
            className={classNames("all", sty.text15)}
          >
            <div className={classNames("all", "__wab_text", sty.text__nVoZx)}>
              {"BUILT WITH LOVE FOR THE WEBFLOW COMMUNITY"}
            </div>
          </div>
          <div
            data-plasmic-name={"text16"}
            data-plasmic-override={overrides.text16}
            className={classNames("all", sty.text16)}
          >
            <div className={classNames("all", "__wab_text", sty.text__nT06P)}>
              {"|"}
            </div>
          </div>
        </div>
      </div>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  tickerHeader: [
    "tickerHeader",
    "container",
    "container2",
    "text",
    "text2",
    "container3",
    "text3",
    "text4",
    "container4",
    "text5",
    "text6",
    "container5",
    "text7",
    "text8",
    "container6",
    "container7",
    "text9",
    "text10",
    "container8",
    "text11",
    "text12",
    "container9",
    "text13",
    "text14",
    "container10",
    "text15",
    "text16"
  ],
  container: [
    "container",
    "container2",
    "text",
    "text2",
    "container3",
    "text3",
    "text4",
    "container4",
    "text5",
    "text6",
    "container5",
    "text7",
    "text8"
  ],
  container2: ["container2", "text", "text2"],
  text: ["text"],
  text2: ["text2"],
  container3: ["container3", "text3", "text4"],
  text3: ["text3"],
  text4: ["text4"],
  container4: ["container4", "text5", "text6"],
  text5: ["text5"],
  text6: ["text6"],
  container5: ["container5", "text7", "text8"],
  text7: ["text7"],
  text8: ["text8"],
  container6: [
    "container6",
    "container7",
    "text9",
    "text10",
    "container8",
    "text11",
    "text12",
    "container9",
    "text13",
    "text14",
    "container10",
    "text15",
    "text16"
  ],
  container7: ["container7", "text9", "text10"],
  text9: ["text9"],
  text10: ["text10"],
  container8: ["container8", "text11", "text12"],
  text11: ["text11"],
  text12: ["text12"],
  container9: ["container9", "text13", "text14"],
  text13: ["text13"],
  text14: ["text14"],
  container10: ["container10", "text15", "text16"],
  text15: ["text15"],
  text16: ["text16"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  tickerHeader: "div";
  container: "div";
  container2: "div";
  text: "div";
  text2: "div";
  container3: "div";
  text3: "div";
  text4: "div";
  container4: "div";
  text5: "div";
  text6: "div";
  container5: "div";
  text7: "div";
  text8: "div";
  container6: "div";
  container7: "div";
  text9: "div";
  text10: "div";
  container8: "div";
  text11: "div";
  text12: "div";
  container9: "div";
  text13: "div";
  text14: "div";
  container10: "div";
  text15: "div";
  text16: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicTickerHeader__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicTickerHeader__VariantsArgs;
    args?: PlasmicTickerHeader__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicTickerHeader__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicTickerHeader__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicTickerHeader__ArgProps,
          internalVariantPropNames: PlasmicTickerHeader__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicTickerHeader__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "tickerHeader") {
    func.displayName = "PlasmicTickerHeader";
  } else {
    func.displayName = `PlasmicTickerHeader.${nodeName}`;
  }
  return func;
}

export const PlasmicTickerHeader = Object.assign(
  // Top-level PlasmicTickerHeader renders the root element
  makeNodeComponent("tickerHeader"),
  {
    // Helper components rendering sub-elements
    container: makeNodeComponent("container"),
    container2: makeNodeComponent("container2"),
    text: makeNodeComponent("text"),
    text2: makeNodeComponent("text2"),
    container3: makeNodeComponent("container3"),
    text3: makeNodeComponent("text3"),
    text4: makeNodeComponent("text4"),
    container4: makeNodeComponent("container4"),
    text5: makeNodeComponent("text5"),
    text6: makeNodeComponent("text6"),
    container5: makeNodeComponent("container5"),
    text7: makeNodeComponent("text7"),
    text8: makeNodeComponent("text8"),
    container6: makeNodeComponent("container6"),
    container7: makeNodeComponent("container7"),
    text9: makeNodeComponent("text9"),
    text10: makeNodeComponent("text10"),
    container8: makeNodeComponent("container8"),
    text11: makeNodeComponent("text11"),
    text12: makeNodeComponent("text12"),
    container9: makeNodeComponent("container9"),
    text13: makeNodeComponent("text13"),
    text14: makeNodeComponent("text14"),
    container10: makeNodeComponent("container10"),
    text15: makeNodeComponent("text15"),
    text16: makeNodeComponent("text16"),

    // Metadata about props expected for PlasmicTickerHeader
    internalVariantProps: PlasmicTickerHeader__VariantProps,
    internalArgProps: PlasmicTickerHeader__ArgProps
  }
);

export default PlasmicTickerHeader;
/* prettier-ignore-end */
