/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

// This code is auto-generated by Plasmic; please do not edit!
// Plasmic Project: xfguyo8p9zs8FxMdioQAoN

import { createUseStyleTokens } from "@plasmicapp/react-web";

import { _useGlobalVariants } from "./plasmic"; // plasmic-import: xfguyo8p9zs8FxMdioQAoN/projectModule

const data = {
  base: `${"plasmic_tokens_xfguyo8p9zs8FxMdioQAoN"}`,
  varianted: []
};

export const _useStyleTokens = createUseStyleTokens(data, _useGlobalVariants);
