/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

// This code is auto-generated by Plasmic; please do not edit!
// Plasmic Project: xfguyo8p9zs8FxMdioQAoN

import * as React from "react";

import { _useGlobalVariants } from "./plasmic"; // plasmic-import: xfguyo8p9zs8FxMdioQAoN/projectModule
import { ContentfulCredentialsProvider } from "@plasmicpkgs/plasmic-contentful";

export interface GlobalContextsProviderProps {
  children?: React.ReactElement;
  contentfulCredentialsProviderProps?: Partial<
    Omit<React.ComponentProps<typeof ContentfulCredentialsProvider>, "children">
  >;
}

export default function GlobalContextsProvider(
  props: GlobalContextsProviderProps
) {
  const { children, contentfulCredentialsProviderProps } = props;

  return (
    <ContentfulCredentialsProvider
      {...contentfulCredentialsProviderProps}
      accessToken={
        contentfulCredentialsProviderProps &&
        "accessToken" in contentfulCredentialsProviderProps
          ? contentfulCredentialsProviderProps.accessToken!
          : "aWvf6oSLTuqxKCxSUpokajdQr84hGQFE6zoJG7DVVLg"
      }
      environment={
        contentfulCredentialsProviderProps &&
        "environment" in contentfulCredentialsProviderProps
          ? contentfulCredentialsProviderProps.environment!
          : "master"
      }
      space={
        contentfulCredentialsProviderProps &&
        "space" in contentfulCredentialsProviderProps
          ? contentfulCredentialsProviderProps.space!
          : "lmfbwqzbh93n"
      }
    >
      {children}
    </ContentfulCredentialsProvider>
  );
}
