// This is a skeleton starter React page generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import { PageParamsProvider as PageParamsProvider__ } from "@plasmicapp/react-web/lib/host";
import GlobalContextsProvider from "../components/plasmic/son_vo/PlasmicGlobalContextsProvider";

// 1. Import chính xác PlasmicHomepage
import { PlasmicHomepage } from "../components/plasmic/son_vo/PlasmicHomepage";
import { useRouter } from "next/router";
import { PlasmicQueryDataProvider } from "@plasmicapp/react-web/lib/query";
import type { GetStaticProps } from "next";
import { extractPlasmicQueryData } from "@plasmicapp/react-web/lib/prepass";

export const getStaticProps: GetStaticProps = async context => {
  // 2. Trích xuất dữ liệu cho PlasmicHomepage
  const queryCache = await extractPlasmicQueryData(<PlasmicHomepage />);
  return {
    props: { queryCache },
    revalidate: 60,
  };
};

function Homepage({ queryCache }: { queryCache?: any }) {
  // Use PlasmicHomepage to render this component as it was
  // designed in Plasmic, by activating the appropriate variants,
  // attaching the appropriate event handlers, etc.

  return (
    <GlobalContextsProvider>
      <PlasmicQueryDataProvider prefetchedCache={queryCache}>
        <PageParamsProvider__
          route={useRouter()?.pathname}
          params={useRouter()?.query}
          query={useRouter()?.query}
        >
          {/* 3. Hiển thị component PlasmicHomepage */}
          <PlasmicHomepage />
        </PageParamsProvider__>
      </PlasmicQueryDataProvider>
    </GlobalContextsProvider>
  );
}

export default Homepage;