/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

// This code is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 22U3ZXm4dE59qEW488gxzU

import { createUseStyleTokens } from "@plasmicapp/react-web";

import { _useGlobalVariants } from "./plasmic"; // plasmic-import: 22U3ZXm4dE59qEW488gxzU/projectModule

import projectcss from "./plasmic.css"; // plasmic-import: 22U3ZXm4dE59qEW488gxzU/projectcss

const data = {
  base: `${projectcss.plasmic_tokens}`,
  varianted: []
};

export const _useStyleTokens = createUseStyleTokens(data, _useGlobalVariants);
