/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

// This code is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 22U3ZXm4dE59qEW488gxzU

import { createUseStyleTokens } from "@plasmicapp/react-web";

import { _useGlobalVariants } from "./plasmic"; // plasmic-import: 22U3ZXm4dE59qEW488gxzU/projectModule

const data = {
  base: `${"plasmic_tokens_22U3ZXm4dE59qEW488gxzU"}`,
  varianted: []
};

export const _useStyleTokens = createUseStyleTokens(data, _useGlobalVariants);
